mercadopago/px-android

example/src/main/java/com/mercadopago/examples/Step8/F2Activity.java, example/src/main/java/com/mercadopago/examples/step1/Step1Activity.java, example/src/main/java/com/mercadopago/examples/step7/Step7Activity.java, sdk/src/androidTest/java/com/mercadopago/PaymentVaultActivityTest.java, sdk/src/androidTest/java/com/mercadopago/model/CheckoutPreferenceTest.java, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/constants/PaymentMethods.java, sdk/src/main/java/com/mercadopago/constants/PaymentTypes.java, sdk/src/main/java/com/mercadopago/constants/Sites.java, sdk/src/main/java/com/mercadopago/model/PaymentMethodSearch.java, sdk/src/main/java/com/mercadopago/model/PaymentMethods.java, sdk/src/main/java/com/mercadopago/model/PaymentPreference.java, sdk/src/main/java/com/mercadopago/model/PaymentType.java
Se agregaron todos los medios de pago para cada site en la clase PaymentMethods
=> List of paymentMethods for site

sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/GuessingCardActivity.java, sdk/src/main/java/com/mercadopago/fragments/CardBackFragment.java, sdk/src/main/java/com/mercadopago/fragments/CardFrontFragment.java, sdk/src/main/java/com/mercadopago/util/MPAnimationUtils.java, sdk/src/main/res/anim/mpsdk_anticipate_overshoot_interpolator.xml, sdk/src/main/res/anim/mpsdk_appear_from_left.xml, sdk/src/main/res/anim/mpsdk_appear_from_right.xml, sdk/src/main/res/anim/mpsdk_dissapear_to_left.xml, sdk/src/main/res/anim/mpsdk_dissapear_to_right.xml, sdk/src/main/res/anim/mpsdk_from_middle_left.xml, sdk/src/main/res/anim/mpsdk_hold.xml, sdk/src/main/res/anim/mpsdk_overshoot_interpolator.xml, sdk/src/main/res/anim/mpsdk_quick_anim.xml, sdk/src/main/res/anim/mpsdk_slide_left_to_right_in_slower.xml, sdk/src/main/res/anim/mpsdk_slide_left_to_right_out_slower.xml, sdk/src/main/res/anim/mpsdk_slide_right_to_left_in_slower.xml, sdk/src/main/res/anim/mpsdk_slide_right_to_left_out_slower.xml, sdk/src/main/res/anim/mpsdk_to_middle_left.xml, sdk/src/main/res/animator/mpsdk_card_flip_left_in.xml, sdk/src/main/res/animator/mpsdk_card_flip_left_out.xml, sdk/src/main/res/animator/mpsdk_card_flip_right_in.xml, sdk/src/main/res/animator/mpsdk_card_flip_right_out.xml, sdk/src/main/res/layout/mpsdk_activity_new_card_form.xml, sdk/src/main/res/layout/mpsdk_new_card_back.xml, sdk/src/main/res/layout/mpsdk_new_card_front.xml, sdk/src/main/res/values/dimens.xml, sdk/src/main/res/values/integers.xml
Se mejoraron las animaciones, haciendo diferencias en algunos casos dependiendo del Api Level del dispositivo.
- Colorear la tarjeta: Se mejoró para api level mayor o igual a Lollipop (api 21)
- Dar vuelta la tarjeta: Se mejoró para api level mayor o igual a Honeycomb mr1 (api 12)
- Deslizamiento de la tarjeta: Al mostrar el documento se mejora en todos los api levels
- Animación entre activities: Se mejora en todos los api levels
=> Mejoras en animaciones

sdk/src/main/java/com/mercadopago/BankDealsActivity.java, sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/CustomerCardsActivity.java, sdk/src/main/java/com/mercadopago/GuessingCardActivity.java, sdk/src/main/java/com/mercadopago/InstructionsActivity.java, sdk/src/main/java/com/mercadopago/MercadoPagoActivity.java, sdk/src/main/java/com/mercadopago/PaymentMethodsActivity.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java, sdk/src/main/java/com/mercadopago/TermsAndConditionsActivity.java, sdk/src/main/java/com/mercadopago/model/DecorationPreference.java
Sólo recibe DecorationPreference.
El método getActivityParameters pasa a ser abstracto.
Cambio el orden de los métodos abstractos de la clase.
=> Cambio en MercadoPagoActivity: deja de recibir parámetros.

sdk/src/main/AndroidManifest.xml, sdk/src/main/java/com/mercadopago/CallForAuthorizeActivity.java, sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/CongratsActivity.java, sdk/src/main/java/com/mercadopago/PendingActivity.java, sdk/src/main/java/com/mercadopago/RejectionActivity.java, sdk/src/main/java/com/mercadopago/ResultActivity.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/res/layout/activity_call_for_authorize.xml, sdk/src/main/res/layout/activity_pending.xml, sdk/src/main/res/layout/activity_rejection.xml, sdk/src/main/res/layout/activity_result.xml
Se creo el componente Result, el cual recibe un payment y un paymentMethod y arroja la pantalla Congrats, Rejection, CallForAuthorize, Pending o Instructions según corresponda.
=> Refactor result

sdk/src/main/java/com/mercadopago/util/MPAnimationUtils.java
Agregué clear animation para evitar parpadeos en la animación del fade in - fade out
=> Fixed blink in api 10

sdk/src/androidTest/assets/mocks/installments.json, sdk/src/androidTest/assets/mocks/payerCosts.json, sdk/src/androidTest/assets/mocks/payerCostsInvalid.json, sdk/src/androidTest/java/com/mercadopago/CheckoutActivityTest.java, sdk/src/androidTest/java/com/mercadopago/InstallmentsActivityTest.java, sdk/src/androidTest/java/com/mercadopago/IssuersActivityTest.java, sdk/src/androidTest/java/com/mercadopago/test/StaticMock.java, sdk/src/main/java/com/mercadopago/InstallmentsActivity.java
- IssuersActivityTests: Cobertura 92% Instrucciones, 91% Branches
- InstallmentsActivityTests: Cobertura 82%, 68% Branches
=> Se agregan tests de IssuersActivity y InstallmentsActivity

sdk/src/androidTest/assets/mocks/customer.json, sdk/src/androidTest/java/com/mercadopago/CustomerCardsActivityTests.java, sdk/src/androidTest/java/com/mercadopago/model/AllModelTest.java, sdk/src/androidTest/java/com/mercadopago/model/CardTest.java, sdk/src/androidTest/java/com/mercadopago/model/SavedCardTokenTest.java, sdk/src/androidTest/java/com/mercadopago/test/StaticMock.java, sdk/src/main/java/com/mercadopago/CustomerCardsActivity.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/java/com/mercadopago/util/JsonUtil.java
Cobertura de líneas: 98%
Cobertura de branches 100%
Además, se modificó el método toJson de JsonUtils, porque fallaba al serializar una lista.
Se agrega asset con json de customer (tiene las tarjetas).
=> Se agregan tests de CustomerCardsActivity

sdk/src/androidTest/assets/mocks/api_exception_not_found.json, sdk/src/androidTest/java/com/mercadopago/ErrorActivityTest.java, sdk/src/androidTest/java/com/mercadopago/test/StaticMock.java
Cobertura de líneas: 100%
Cobertura de branches: 100%
=> Se agregan tests de ErrorActivity

sdk/src/androidTest/java/com/mercadopago/PaymentVaultActivityTest.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java
Cobertura de líneas: 100%
Cobertura de branches: 93%
=> Se agregan tests de PaymentVaultActivity

sdk/src/androidTest/java/com/mercadopago/CustomerCardsActivityTests.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/java/com/mercadopago/util/JsonUtil.java
Se corrige un bug en la versión previa.
=> Fix serialización de listas

sdk/src/androidTest/java/com/mercadopago/InstallmentsActivityTest.java, sdk/src/main/java/com/mercadopago/InstallmentsActivity.java
Se agregaron tests sobre respuestas erróneas de API, de cuotas por defecto y de reintento ante falla de API (Ej. Timeout).
Cobertura de líneas: 92%
Cobertura de branches: 91%
=> Se agregan tests de InstallmentsActivity

sdk/src/main/java/com/mercadopago/model/DecorationPreference.java
Se agrega la posibilidad de ingresar el color base como un hexa:
`decorationPreference.setBaseColor("#F8DADA");`
=> Decoration preference: base color con hexa

sdk/src/main/java/com/mercadopago/core/MercadoPago.java
Refactor de llamada a PaymentResultActivity en MercadoPago
=> Refactor de llamada a PaymentResult

sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java
Refactor de llamada pública a PaymentResultActivity
=> Refactor de llamada pública a PaymentResultActivity

sdk/build.gradle, sdk/src/main/java/com/mercadopago/BankDealsActivity.java, sdk/src/main/java/com/mercadopago/CallForAuthorizeActivity.java, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/CongratsActivity.java, sdk/src/main/java/com/mercadopago/CustomerCardsActivity.java, sdk/src/main/java/com/mercadopago/ErrorActivity.java, sdk/src/main/java/com/mercadopago/GuessingCardActivity.java, sdk/src/main/java/com/mercadopago/InstallmentsActivity.java, sdk/src/main/java/com/mercadopago/InstructionsActivity.java, sdk/src/main/java/com/mercadopago/IssuersActivity.java, sdk/src/main/java/com/mercadopago/PaymentMethodsActivity.java, sdk/src/main/java/com/mercadopago/PaymentResultActivity.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java, sdk/src/main/java/com/mercadopago/PendingActivity.java, sdk/src/main/java/com/mercadopago/RejectionActivity.java, sdk/src/main/java/com/mercadopago/TermsAndConditionsActivity.java, sdk/src/main/java/com/mercadopago/adapters/ErrorHandlingCallAdapter.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/res/values/strings.xml
Se modificó el tipo de dato del parámetro flavor en todos los tracks. Antes era un string, ahora es un integer.
Se agregaron tracks sin solicitar el siteId por parámetro.
Se cambió la versión del SDK. Antes era un string hardcodeado, ahora se toma del gradle.
Se eliminaron tracks que brindaban información no relevante.
=> Tracking review

sdk/src/androidTest/java/com/mercadopago/InstallmentsActivityTest.java, sdk/src/androidTest/java/com/mercadopago/IssuersActivityTest.java, sdk/src/main/java/com/mercadopago/BankDealsActivity.java, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/MercadoPagoActivity.java, sdk/src/main/java/com/mercadopago/PaymentMethodsActivity.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java, sdk/src/main/java/com/mercadopago/ShowCardActivity.java, sdk/src/main/java/com/mercadopago/TermsAndConditionsActivity.java
- Se arregló el dark font enabled en IssuersActivity y InstallmentsActivity
- Se arregló el color de la toolbar en CardVaultActivity
- Se agregaron tests que validan los casos anteriores
=> Fix de decoration preference con dark font

checkout_custom.html, f1.html, f2.html, index.html
=> Documentación actualizada para v1.0.0

sdk/src/androidTest/java/com/mercadopago/GuessingCardActivityTest.java, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/res/layout/mpsdk_identification_card_front.xml
- Fix de tests de guessing 
- Fix de visualización del documento para el caso CNPJ
- Fix en CardVault para que finalice la activity
=> Fixes varios para release 

sdk/src/main/res/layout/mpsdk_identification_card_front.xml, sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml
El formulario de ingreso del documento del titular de la tarjeta se cambio el string "DOCUMENTO DEL TITULAR DE LA TARJETA". Antes eran dos strings, ahora es uno con un salto de línea. Se modificó para Español, Inglés y Portugués.
En guessing se cambió "Last name" por "surname" para que se vea el string completo en el formulario y "First name" por "Name".
Se cambió "MercadoPago" por "Mercado Pago" en los strings en Español, Inglés y Portugués
=> Fix strings

en-checkout_custom.html, en-f1.html, en-f2.html, en-index.html
Files:
- en-checkout_custom.html
- en-f1.html
- en-f2.html
- en-index.html
=> English docs

example/src/main/java/com/mercadopago/examples/components/ComponentsExampleActivity.java, example/src/main/res/values-en/strings.xml, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/PaymentResultActivity.java
Toolbar blink in issuers-to-installment transition.
Example strings correction.
PaymentResult action when error occurs.
=> Some fixes

sdk/src/androidTest/java/com/mercadopago/CallForAuthorizeActivityTest.java, sdk/src/androidTest/java/com/mercadopago/CongratsActivityTest.java, sdk/src/androidTest/java/com/mercadopago/RejectionActivityTest.java, sdk/src/main/java/com/mercadopago/CallForAuthorizeActivity.java, sdk/src/main/java/com/mercadopago/CongratsActivity.java, sdk/src/main/java/com/mercadopago/RejectionActivity.java, sdk/src/main/res/layout/mpsdk_activity_congrats.xml, sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml
Se unificaron strings que estaban divididos. 
Se agregaron variables en los strings unificados.
Se agregaron las traducciones al portugués y al inglés.
Se eliminaron los strings que no se estaban utilizando.
Se ordenaron los strings por activity.
=> Refactor strings

sdk/src/androidTest/java/com/mercadopago/PaymentMethodsActivityTest.java, sdk/src/main/res/layout/mpsdk_activity_payment_methods.xml, sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml
Se actualizaron los strings en Portugués con las correcciones realizadas por Comunicaciones
=> Portuguese strings updated

sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values/strings.xml
Se corrigieron detalles en algunos strings.
//Description
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
=> English strings

README.md
Nuevo readme para el repositorio:
[https://github.com/mercadopago/px-android/tree/new-readme](https://github.com/mercadopago/px-android/tree/new-readme)
=> [Docs] New readme

sdk/build.gradle, sdk/src/main/AndroidManifest.xml, sdk/src/main/java/com/mercadopago/CardVaultActivity.java
Se agrega Tracker 1.2.1.
Se agrega fix en C4A.
=> [Release] Release 2.3.1

example/src/main/java/com/mercadopago/examples/checkout/CheckoutExampleActivity.java, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/DiscountsActivity.java, sdk/src/main/java/com/mercadopago/GuessingCardActivity.java, sdk/src/main/java/com/mercadopago/InstallmentsActivity.java, sdk/src/main/java/com/mercadopago/MercadoPagoBaseActivity.java, sdk/src/main/java/com/mercadopago/PaymentMethodsActivity.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/java/com/mercadopago/core/MercadoPagoUI.java, sdk/src/main/java/com/mercadopago/presenters/CardVaultPresenter.java, sdk/src/main/java/com/mercadopago/presenters/DiscountsPresenter.java, sdk/src/main/java/com/mercadopago/presenters/GuessingCardPresenter.java, sdk/src/main/java/com/mercadopago/presenters/InstallmentsPresenter.java, sdk/src/main/java/com/mercadopago/presenters/PaymentVaultPresenter.java, sdk/src/main/java/com/mercadopago/uicontrollers/discounts/DiscountRowView.java, sdk/src/main/res/layout/mpsdk_row_discount.xml, sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, sdk/src/test/java/com/mercadopago/discounts/DiscountsPresenterTest.java
- Se agrego la posibilidad de apagar el feature Discount.
Por default el feature de descuentos está prendido. 
En caso de estar prendido y contar con un descuento aplicable, se comunica el descuento.
En caso de estar el feature apagado, se muestra el total amount.
Por default, si no hay descuento, en la Discount row se ve el total amount. 
En caso de existir descuento, se comunica el descuento. 
**Discount feature off**
**Discount feature on**
=> [Enhancement] Total amount visible in Discount row

sdk/src/main/java/com/mercadopago/CongratsActivity.java, sdk/src/main/java/com/mercadopago/PendingActivity.java, sdk/src/main/java/com/mercadopago/RejectionActivity.java, sdk/src/main/java/com/mercadopago/preferences/FlowPreference.java
Cambios en los tracks para Wallet.
Fix en flujo con Pref real.
=> [Fix] In flow with real preferences. Changed result tracks.

en-f2.html, f2.html
- Se agrega la documentación correspondiente al feature de Descuentos en inglés y español.
- Se agrega la documentación correspondiente al feature Timer en inglés y español.
Closes #424
=> Discounts documentation

px-tracking/src/androidTest/java/com/mercadopago/px_tracking/MPTrackerTest.java, px-tracking/src/main/java/com/mercadopago/px_tracking/MPTracker.java, px-tracking/src/main/java/com/mercadopago/px_tracking/services/MPTrackingService.java, px-tracking/src/main/java/com/mercadopago/px_tracking/services/MPTrackingServiceImpl.java, px-tracking/src/main/java/com/mercadopago/px_tracking/strategies/RealTimeTrackingStrategy.java, px-tracking/src/main/java/com/mercadopago/px_tracking/strategies/TrackingStrategy.java, sdk/src/main/java/com/mercadopago/providers/MPTrackingProvider.java
Se abstrae al tracker de la implementación del envío final.
=> [Tracking] Added tracking strategies

sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/constants/ProcessingModes.java, sdk/src/main/java/com/mercadopago/core/MercadoPago.java, sdk/src/main/java/com/mercadopago/core/MercadoPagoServices.java, sdk/src/main/java/com/mercadopago/model/PaymentMethod.java, sdk/src/main/java/com/mercadopago/preferences/ServicePreference.java, sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java, sdk/src/main/java/com/mercadopago/services/CheckoutService.java, sdk/src/main/java/com/mercadopago/services/PaymentService.java, sdk/src/test/java/com/mercadopago/preferences/ServicePreferenceTest.java
//Description
Se da soporte al modo gateway.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> [Feature] Gateway Mode

CHANGELOG-v3.md, README.md, px-tracking/src/androidTest/assets/mocks/expired_screen_view_event.json, px-tracking/src/androidTest/assets/mocks/screen_view_event.json, px-tracking/src/main/java/com/mercadopago/px_tracking/model/ActionEvent.java, px-tracking/src/main/java/com/mercadopago/px_tracking/model/ErrorEvent.java, px-tracking/src/main/java/com/mercadopago/px_tracking/model/Event.java, px-tracking/src/main/java/com/mercadopago/px_tracking/model/ScreenViewEvent.java, px-tracking/src/main/java/com/mercadopago/px_tracking/strategies/BatchTrackingStrategy.java, px-tracking/src/main/java/com/mercadopago/px_tracking/strategies/EventsDatabase.java, px-tracking/src/main/java/com/mercadopago/px_tracking/strategies/EventsDatabaseImpl.java, px-tracking/src/main/java/com/mercadopago/px_tracking/utils/HttpClientUtil.java, sdk/build.gradle, sdk/src/main/java/com/mercadopago/ReviewAndConfirmActivity.java
_31_08_2017_
* HotFix: Time in millis in tracking
* HotFix: Floating button in RyC
=> [Hotfix] 3.4.1

CHANGELOG-v3.md, README.md, sdk/src/main/java/com/mercadopago/CardVaultActivity.java, sdk/src/main/java/com/mercadopago/presenters/GuessingCardPresenter.java
=> [Hotfix] 3.4.3 to develop

sdk/src/main/java/com/mercadopago/CongratsActivity.java, sdk/src/main/java/com/mercadopago/preferences/PaymentResultScreenPreference.java
Se agrega la posibilidad de customizar la imagen de la pantalla de pago aprobado.
`````java
PaymentResultScreenPreference preference = new PaymentResultScreenPreference.Builder()
.setApprovedHeaderIcon(R.drawable.mpsdk_tc_with_container)
.build();
new MercadoPagoCheckout.Builder()
.setActivity(this)
.setPublicKey(mPublicKey)
.setPaymentResultScreenPreference(preference)
.setCheckoutPreference(getCheckoutPreference())
.setDecorationPreference(getCurrentDecorationPreference())
.startForPayment();
``````
=> [Enhancement] Customized approved payment header image

sdk/src/main/java/com/mercadopago/providers/ReviewAndConfirmProviderImpl.java
Se aplica el hotfix en los cargos en el nuevo Summary.
=> [Hotfix] Summary charges

CHANGELOG-v3.md, README.md, sdk/build.gradle
_21_09_2017_
* Fix: Summary charges in RyC
=> [Update] Version 3.5.1

CHANGELOG-v3.md, README.md, sdk/build.gradle, sdk/src/main/java/com/mercadopago/providers/ReviewAndConfirmProviderImpl.java
21_09_2017
Fix: Summary charges in RyC
=> [Hotfix] 3.5.1 to develop

CHANGELOG-v3.md, README.md
=> [Docs] Version 3.5.2

sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/core/MercadoPagoCheckout.java, sdk/src/main/java/com/mercadopago/preferences/FlowPreference.java, sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java, sdk/src/main/java/com/mercadopago/views/CheckoutView.java, sdk/src/test/java/com/mercadopago/checkout/CheckoutPresenterTest.java
Se permite salir del Checkout tras un cambio o cancel en RyC.
=> [Feature] Exit from RyC on Change

sdk/src/main/java/com/mercadopago/providers/ReviewAndConfirmProviderImpl.java
Se corrige crash en la selección de medios off.
=> [Fix] Offline payment methods

sdk/src/main/java/com/mercadopago/components/Action.java, sdk/src/main/java/com/mercadopago/components/ActionDispatcher.java, sdk/src/main/java/com/mercadopago/components/ActionsListener.java, sdk/src/main/java/com/mercadopago/components/Component.java, sdk/src/main/java/com/mercadopago/components/ComponentManager.java, sdk/src/main/java/com/mercadopago/components/Mutator.java, sdk/src/main/java/com/mercadopago/components/MutatorPropsListener.java, sdk/src/main/java/com/mercadopago/components/Renderer.java, sdk/src/main/java/com/mercadopago/components/RendererFactory.java
Se agregan las clases básicas para poder crear componentes y renderers.
=> Components framework

sdk/src/main/java/com/mercadopago/components/Component.java, sdk/src/main/java/com/mercadopago/components/ComponentManager.java, sdk/src/main/java/com/mercadopago/components/LoadingComponent.java, sdk/src/main/java/com/mercadopago/components/LoadingRenderer.java, sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultActivity.java, sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultPropsMutator.java, sdk/src/main/java/com/mercadopago/paymentresult/components/HeaderComponent.java, sdk/src/main/java/com/mercadopago/paymentresult/components/IconComponent.java, sdk/src/main/java/com/mercadopago/paymentresult/components/PaymentResultBodyComponent.java, sdk/src/main/java/com/mercadopago/paymentresult/components/PaymentResultContainer.java, sdk/src/main/java/com/mercadopago/paymentresult/components/PaymentResultFooterComponent.java, sdk/src/main/java/com/mercadopago/paymentresult/props/PaymentResultProps.java, sdk/src/main/java/com/mercadopago/paymentresult/renderers/HeaderRenderer.java, sdk/src/main/java/com/mercadopago/paymentresult/renderers/IconRenderer.java, sdk/src/main/java/com/mercadopago/paymentresult/renderers/PaymentResultBodyRenderer.java, sdk/src/main/java/com/mercadopago/paymentresult/renderers/PaymentResultFooterRenderer.java, sdk/src/main/java/com/mercadopago/paymentresult/renderers/PaymentResultRenderer.java, sdk/src/main/res/layout/mpsdk_component_loading.xml
//Description
- Nuevo componente Loading
- Limpieza general de código
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> Loading component and code clean

CHANGELOG-v3.md, README.md
Se actualiza el Changelog y el Readme.
=> Updated changelog and readme (#737)

CHANGELOG-v3.md
=> [Docs] Added two fixes description in Changelog (#739)

example/src/main/java/com/mercadopago/hooks/ExampleHooks.java, sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/components/Component.java, sdk/src/main/java/com/mercadopago/core/MercadoPagoCheckout.java, sdk/src/main/java/com/mercadopago/core/PreferenceStore.java, sdk/src/main/java/com/mercadopago/hooks/CheckoutHooks.java, sdk/src/main/java/com/mercadopago/hooks/DefaultCheckoutHooks.java, sdk/src/main/java/com/mercadopago/hooks/Hook.java, sdk/src/main/java/com/mercadopago/hooks/HookComponent.java, sdk/src/main/java/com/mercadopago/hooks/HookRenderer.java, sdk/src/main/java/com/mercadopago/hooks/HooksStore.java, sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java, sdk/src/main/java/com/mercadopago/presenters/PaymentVaultPresenter.java
Remove unnecesary info from HookComponent creation from the integrator, hide the complexity from integrator.
=> [Enhancement] Hooks: remove unnecesary info from integrator

sdk/src/main/java/com/mercadopago/paymentresult/components/BodyErrorRenderer.java, sdk/src/main/res/layout/mpsdk_payment_result_body_error.xml
=> [Fix] Stretch error component

sdk/src/main/java/com/mercadopago/customviews/MPEditText.java
- Se deshabilita el Autofill para todos los MPEditText.
=> [Enhancement] Disabling autofill

sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultActivity.java, sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultNavigator.java, sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultPresenter.java, sdk/src/test/java/com/mercadopago/paymentresult/PaymentResultTest.java
- Se agrega el track para las pantallas de resultado
=> [Fix] Tracking screens

sdk/src/main/java/com/mercadopago/CheckoutActivity.java, sdk/src/main/java/com/mercadopago/MercadoPagoBaseActivity.java, sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java
//Description
Se actualizan transiciones entre activities.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> Transitions review

sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultActivity.java, sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultPresenter.java
//Description
Fixes crash on congrats when activity restore.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> Crash Android PX congrats result

sdk/src/main/java/com/mercadopago/model/Discount.java
Se agrega un campo de id de campaña del discount
=> Add campaign id to the discount dto

sdk/src/main/java/com/mercadopago/providers/ReviewAndConfirmProviderImpl.java, sdk/src/main/res/layout/mpsdk_activity_review_confirm.xml, sdk/src/main/res/values-en/strings.xml, sdk/src/main/res/values-es/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml
//Description
Cambios de wordings, en todos los idiomas.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> Fix wordings

sdk/src/main/res/values-pt/strings.xml
//Description
Se agrega un wording en portugues que faltaba.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> [Fix] Wording

sdk/src/main/java/com/mercadopago/preferences/CheckoutPreference.java
Se agregan 3 campos al DTO de checkout preference para poder procesar nuevos tipos de pagos
=> Add new fields to checkoutPreference DTO

sdk/src/main/res/values/colors.xml
//Description
Se cambió el color de los circulos para que coincida con IOS.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> [Fix] Circle color fixed

gradle.properties, sdk/build.gradle, sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java
//Description
Update gson version to 2.8.2, because older version has a bug with null dates.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
=> [Fix] Fix gson version

gradle.properties, sdk/build.gradle, sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java
=> V3 to master

CHANGELOG-v3.md, README.md
=> [Update] Version number in changelog and readme

gradle.properties, gradle/deploy.gradle, sdk/build.gradle
Se agrega configuración de deploy para ./gradlew install y ./gradle bintrayUpload
Luego de correrlo se detectó lo siguiente:
Headers incorrectos de documentación de clases.
Necesidad de agregar paquetes de exclusión para que no sea disponible toda la doc de las clases.
=> [feature] javadocs

sdk/src/main/java/com/mercadopago/paymentresult/components/PaymentResultContainer.java, sdk/src/main/java/com/mercadopago/paymentresult/props/PaymentResultBodyProps.java
- bugfix generado por error en amount.
=> [bugfix] amount in body

gradle/deploy_tracking.gradle
fix artifact deploy for tracking
=> [bugfix] deploy tracking

services/src/main/java/com/mercadopago/model/PaymentMethod.java
Caso generaba null pointer exception - atributos min and max no vienen en caso de plugin y no estaba contemplado.
=> [bugfix] payment method min and max allowed amount

gradle.properties
[release] 4.0.0-beta-32.0.3 version bump
=> [release] 4.0.0-beta-32.0.3 version bump

sdk/src/main/java/com/mercadopago/SecurityCodeActivity.java
No funcionaba el botón de continuar en el teclado en la pantalla de código de seguridad
[Bug en jira](https://mercadolibre.atlassian.net/browse/CONV-71)
=> [Hotfix] Listener in keyboard cvv

px-checkout/src/main/java/com/mercadopago/android/px/model/ExternalFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/review_and_confirm/components/ReviewAndConfirmRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/review_and_confirm/models/ReviewAndConfirmPreferences.java, px-services/src/main/java/com/mercadopago/android/px/preferences/CheckoutPreference.java
https://mercadolibre.atlassian.net/browse/CONN-223
=> [refactor/v4 API signature] deprecated methods review and confirm preference

px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
sugerido por @jsotuyod  en https://github.com/mercadopago/px-android/pull/1119#discussion_r203020410
=> [enhancement] description session / context call

px-checkout/src/main/java/com/mercadopago/android/px/paymentresult/props/HeaderProps.java, px-checkout/src/main/java/com/mercadopago/android/px/plugins/BusinessPaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/plugins/components/BusinessPaymentRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/plugins/model/BusinessPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/plugins/model/BusinessPaymentModel.java, px-services/src/main/java/com/mercadopago/android/px/services/util/ParcelableUtil.java, px-services/src/main/java/com/mercadopago/android/px/services/util/TextUtil.java
Loyalty necesita modificar el subtitulo de business result.
https://mercadolibre.atlassian.net/browse/CONN-239
Efectuar un pago con business con el parametro ```setSubtitle(...)```
Afecta a loyalty
=> [feature/CONN-239] subtitle for business result

example/build.gradle, px-services/build.gradle, px-services/src/main/java/com/mercadopago/android/px/services/core/Settings.java, px-services/src/main/java/com/mercadopago/android/px/services/core/UserAgentInterceptor.java, px-services/src/main/java/com/mercadopago/android/px/services/util/HttpClientUtil.java
https://mercadolibre.atlassian.net/browse/CONN-245
Enviar user agent de cliente android PX con su versión.
ver api call, debe contener user agent
Ejemplo:
Content-Type: application/json; charset=UTF‌-8
Content-Length: 163
Accept-Language: pt
User-Agent: PX/Android/4.0.0-beta-34.0.6
=> [enhancement] User agent for android

CHANGELOG-v4.md, README.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/MercadoPagoPaymentProcessor.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/TokenizeService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/components/BusinessPaymentRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/BodyRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/components/ReviewAndConfirmRenderer.java, px-checkout/src/main/res/values/ids.xml, px-services/src/main/java/com/mercadopago/android/px/model/SavedCardToken.java, px-services/src/main/java/com/mercadopago/android/px/model/SavedESCCardToken.java
* Fix: dynamic id declaration
* Fix: code discount
* Fix: esc with one tap
=> [Hotfix] 4.0.1

px-checkout/src/androidTest/java/com/mercadopago/android/px/test/StaticMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/base/MvpPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/controllers/PaymentMethodGuessingController.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/InstallmentsPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/MercadoPagoComponents.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodePresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/card/CardNumberTextWatcher.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardActivityView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/providers/GuessingCardProvider.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/providers/GuessingCardProviderImpl.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/uicontrollers/card/CardView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/uicontrollers/identification/IdentificationView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/tracker/MPTrackingContext.java, px-checkout/src/test/java/com/mercadopago/android/px/guessing/GuessingCardPresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/securitycode/SecurityCodePresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/utils/CardTestUtils.java, px-services/src/main/java/com/mercadopago/android/px/internal/services/CheckoutService.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/JsonUtil.java, px-services/src/main/java/com/mercadopago/android/px/model/Card.java, px-services/src/main/java/com/mercadopago/android/px/model/CardToken.java, px-services/src/main/java/com/mercadopago/android/px/model/Identification.java, px-services/src/main/java/com/mercadopago/android/px/model/SecurityCode.java, px-services/src/main/java/com/mercadopago/android/px/model/Setting.java
La mayoría son fixes de los warnings de lint, con una pequeña reorganización y reestructuración del código de cara los próximos refactors de PX.
Limpieza de código como primer etapa del refactor del flujo de tarjeta para poder implementar Alta Tarjeta
Lint fixes, algún que otro null check y método movido. Ningún cambio de lógica de negocio
Recorrí el flujo de alta tarjeta manualmente.
=> [Enhancement] Fixing lint warnings, minor refactor

README.md
Se agrega el repo de maven para descargar la Lib de UI de Meli en el Readme para los integradores externos.
=> [Fix] Readme for UI lib

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultProviderImpl.java
Se borran dos variables y dos imports que no se usan.
=> [enhancement] Deleted unused variable

CHANGELOG-v4.md, README.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/CheckoutPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/navigation/DefaultPaymentMethodDriver.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/driver/DefaultPaymentMethodDriverTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/CurrenciesUtil.java
fix default payment type id and currency utils
=> [hotfix] 4.0.4

CHANGELOG-v4.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/onetap/OneTapFragment.java
=> [hotfix] 4.1.1

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/PaymentResultContainer.java
=> Fix PaymentResultContainerTest

px-services/src/main/java/com/mercadopago/android/px/internal/services/CheckoutService.java, px-services/src/main/java/com/mercadopago/android/px/internal/services/InstructionsClient.java
Se sube el api version para que traiga a PEC como payment method y nuevas instrucciones para Boleto y las intrucciones de PEC
=> [feature] Api Version 1.7 Payment Methods y Instructions

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/TitlePagerAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodDescriptorView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodHeaderView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/TitlePager.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/AccountMoneyDescriptor.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/EmptyInstallmentsDescriptor.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/GoingToModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/InstallmentsDescriptorNoPayerCost.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/InstallmentsDescriptorWithPayerCost.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/PayerCostSelection.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/InstallmentsDescriptorMapper.java, px-checkout/src/main/res/layout/px_fragment_express_payment.xml, px-checkout/src/main/res/layout/px_view_installments_header.xml, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenterTest.java
Me falta interfacear el adapter, lo voy a hacer en otro PR cuando meta otro adapter que implemente la misma interfaz.
=> [Refactor] Title pager adapter

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultErrorActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultSuccessActivity.java
_30_11_2018_
* FIX: Crash on Card Association congrats
=> [Hotfix] 4.3.2 to master

px-checkout/src/androidTest/java/com/mercadopago/android/px/model/CardTokenTest.java, px-checkout/src/androidTest/java/com/mercadopago/android/px/test/StaticMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/PaymentVaultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/tracker/Tracker.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/DiscountDetailDialog.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/utils/TrackingUtil.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/AppliedDiscountOneTapView.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/AppliedDiscountView.java
Se estaba trackeando doble la vista de detalle de descuento
=> [refactor] added applied discount view

px-checkout/src/androidTest/java/com/mercadopago/android/px/model/CardTokenTest.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/uicontrollers/paymentmethodsearch/PaymentMethodSearchCustomOption.java, px-checkout/src/main/res/layout/px_row_pm_search_item.xml, px-services/src/main/java/com/mercadopago/android/px/model/CustomSearchItem.java
Según la definición de la nueva versión de descuentos, se pide agregar un label para descuentos con tarjeta.
- Se agrega nuevo MPTextView para DiscountInfo con visibility gone.
- Se agrega lógica en el draw de PaymentMethodSearchCustomOption para visibilizar discount info en caso que corresponda.
Probar con apiAry.
=> [Feature] Label Payment Vault Discount TC

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/InstallmentsActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/InstallmentsPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/PayerCostInfoList.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/utils/TrackingUtil.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/InstallmentsViewTrack.java
=> [feature] view/tracking/installments

example/src/main/res/layout/activity_checkout_example.xml, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/InstallmentsActivity.java, px-checkout/src/main/res/layout/px_activity_installments_lowres.xml, px-checkout/src/main/res/layout/px_activity_installments_normal.xml, px-checkout/src/main/res/layout/px_activity_payment_types_normal.xml, px-checkout/src/main/res/layout/px_new_card_installments.xml, px-checkout/src/main/res/layout/px_scrolling_toolbar.xml, px-checkout/src/main/res/values/colors.xml, px-checkout/src/main/res/values/strings.xml
Solucionar problemas en la pantalla de installments que saltaron en Colombia.
Puntualmente no se llega a ver la última cuota de la lista y tiene mal el color de un label en ML.
=> [Fix] Installments layout recycler clip

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/components/ReviewAndConfirmRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/navigation/DefaultPayerInformationDriver.java
Se arreglan los casos de tarjeta guardada y tarjeta nueva en revisa y confirma
=> [Fix] Payer info driver for cards

px-testlib/src/main/java/com/mercadopago/android/px/testcheckout/pages/PaymentMethodPage.java
Se agregaron metodos para nuevas acciones en pantalla de Payment Method
Se necesitaba seleccionar un medio de pago especifico
No es un breaking change
=> [Feature] Adding step in payment method page needed for new ETE tests

CHANGELOG.md, gradle.properties
_02_01_2019_
* FEATURE - Account money as a first class member.
* FEATURE - Added event and view data for PXTrackingListener class.
* FIX - Crash on back on Sec code saved card.
=> [RELEASE] PX version 4.5.0

.travis.yml, scripts/cd_script.sh
Ahora para deployar un release tiene que ser con el commit "[ci deploy]" y el nombre del branch tiene que empezar con "release/".
Y los PRs normales no corren los tests de Jacoco, solo los "comunes".
=> Travis deploy fixes and improvements

px-checkout/src/main/java/com/mercadopago/android/px/internal/base/MvpPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AmountConfigurationRepositoryImpl.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/ConfigurationSolverImpl.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/HubAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodFragmentAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/SplitPaymentHeaderAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ViewAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/installments/InstallmentsActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/installments/InstallmentsPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/AmountConfigurationRepository.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/LabeledSwitch.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/InstallmentsDescriptorNoPayerCost.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/InstallmentsDescriptorWithPayerCost.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/PaymentMethodDescriptorMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/SplitHeaderMapper.java, px-checkout/src/test/java/com/mercadopago/android/px/cardvault/CardVaultPresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/installments/InstallmentsPresenterTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/RetrofitUtil.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/TextUtil.java, px-services/src/main/java/com/mercadopago/android/px/model/AmountConfiguration.java, px-services/src/main/java/com/mercadopago/android/px/model/CustomSearchItem.java, px-services/src/main/java/com/mercadopago/android/px/model/Split.java, px-services/src/main/java/com/mercadopago/android/px/model/SummaryAmount.java
Agregar el cableado de la row de split payment (on/off)
Se agregó comportamiento on/off para split payment con valores x defecto y persistencia de selección de usuario.
=> [feature] wire dto split with split header view

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/CheckoutActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/PaymentVaultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ErrorUtil.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ReviewAndConfirmViewTracker.java
Bug descripto en issue [PXAN-184](https://mercadolibre.atlassian.net/browse/PXAN-184).
NPE en ReviewAndConfirm causado por no poder persistir aún la Session.
- Se agregan try/catch temporales en onCreate e initContent.
- Se trackean los stacktrace de los crashes.
- Se agrega método para trackear un fancy stacktrace y se modifica en anteriores tracks similares.
=> [Fix]  PXAN-184 :: NPE R&C - getPaymentProcessor()

README.md, px-checkout/src/main/java/com/mercadopago/android/px/core/MercadoPagoCheckout.java
Facilita la integración de un checkout básico al actualizar los links para que apunten a la documentación correspondiente y facilitar un llamado a la API para crear una preferencia de prueba.
- Actualización de link para crear preferencias.
- Se agrega sector dentro del readme donde indica como generar una preferencia.
- Revisar la pagina principal del repo en github para ver el cambio en el readme.
- Revisar link actualizado en documentación de la clase MercadoPagoCheckout.Builder.
=> [enhancement] Update info about create preferences

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/FooterPaymentResult.java
Se está utilizando un String con template sin ser formateado con el dato que corresponde,
- Se agrego formateo del String con el dato correspondiente.
- Generar un escenario donde el Payment tenga de StatusDetail uno de los siguientes:
-- STATUS_DETAIL_CC_REJECTED_BAD_FILLED_DATE
-- STATUS_DETAIL_CC_REJECTED_BAD_FILLED_SECURITY_CODE
-- STATUS_DETAIL_CC_REJECTED_BAD_FILLED_OTHER
-- STATUS_DETAIL_CC_REJECTED_BAD_FILLED_CARD_NUMBER
=> [fix] unformatted string template

px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/InitData.java
* Se agrega split enabled al Init Track
=> [enhancement] Added split enabled to init track

CHANGELOG.md, gradle.properties, px-testlib/src/main/java/com/mercadopago/android/px/testcheckout/pages/IdentificationPage.java
_21_03_2019_
* FEATURE - Issuer images in Cards
* FEATURE - CNPJ payment with Boleto
* FEATURE - Skip congrats in storage card flow
=> [Release] 4.9.0

CHANGELOG.md, gradle.properties
_29_03_2019_
* FIX - Friction rate in id card
=> [Hotfix] 4.9.3

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/plugins/PaymentProcessorActivity.java
Fix para este crash:
https://mercadolibre.atlassian.net/browse/PXN-672
=> [Fix] Trycatching payment processor activity crash

px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/PaymentDataHelper.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.java
Se agrega el trackeo de nuevos atributos en la pantalla de Tracking.
Fueron solicitados desde BI.
=> [feature] Congrats tracking

px-checkout/src/main/java/com/mercadopago/android/px/internal/util/DiscountHelper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/AmountView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/DiscountDetailContainer.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/DiscountDescriptionLocalized.java
Ahora usamos la property "name" del Discount como descripción del mismo.
Por si no viene nada (no debería pasar) en ese caso tenemos un fallback genérico (sincronizado con iOS esto).
=> [Feature] Using discount name for his description

px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ResultViewTrackModel.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.java
Están ocurriendo invalid tracks en los tracks de result debido a que el dto está siendo minificado por no estar dentro de las reglas de proguard.
- Se mueve el dto ResultViewTrackModel.java al package de internal.model, incluido en las reglas de proguard
=> [fix] move dto to package included in proguard rules

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/SummaryAmountService.java, px-services/src/main/java/com/mercadopago/android/px/model/PaymentMethod.java
Reverts mercadopago/px-android#1724
=> Revert "[feature] add payment method processing modes into summary amount request"

px-services/src/main/java/com/mercadopago/android/px/model/PayerCost.java
Reverts mercadopago/px-android#1725
=> Revert "[feature] add param in summary amount response for gateway mode."

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformation.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformationActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformationFocus.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformationPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/PayerInformationStateModel.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformationPresenterTest.java, px-services/src/main/java/com/mercadopago/android/px/model/Payment.java
Terminé haciendo mucho refactor pero estaba medio dudoso ese MVP la verdad.
=> Fix payer information restore instance

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/uicontrollers/card/CardView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/uicontrollers/card/FrontCardView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/MPAnimationUtils.java
Estoy tratando de evitar este crash:
https://app.bugsnag.com/mercadolibre/mercado-pago-android/errors/59317f1d71d83b00182eaba2?event_id=5cdc3f0d003a05f1d67c0000&i=jr&m=ci
=> Prevent circle reveal animation from running if the view isn't attached

px-checkout/src/main/java/com/mercadopago/android/px/internal/callbacks/PaymentServiceHandlerWrapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentRewardRepositoryImpl.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PaymentRewardRepository.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenterTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/services/PaymentRewardService.java
Se agrego campaignId en PaymentRewardRepositoryImpl.
=> added campaignId in reward repository

px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/BaseSecurityRulesTest.java, px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/EscRulesTest.java, px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/RulesTest.java, px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/SecurityCodeRulesTest.java, px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/SecurityRulesTest.java
Se agrego campaignId en PaymentRewardRepositoryImpl.
=> refactor rules test

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultContract.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultContract.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/MercadoPagoUtil.java
Se agrego lógica "safe intent" para la acción de crossselling en congrats.
=> add safeIntent to crossselling action

px-checkout/src/main/res/layout/px_business_components.xml
Se agregó margen en el componente de loyalty para equilibrar con la vista de crossselling.
=> fix margin

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/TermsAndConditionsActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_payment_methods/ReviewPaymentMethodsActivity.java
=> Session inited

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/font/FontHelper.java
Se adapta FontHelper
Por actualizacion de UI a 8.+
=> [Feat] Se actualiza UI a 8.+

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/font/FontHelper.java
Reverts mercadopago/px-android#1903
=> Revert "[Feat] Se actualiza UI a 8.+"

example/build.gradle, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/PxCheckoutInitProvider.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/components/items/ReviewItemRenderer.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/PicassoLoader.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/ElementDescriptorView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultHeader.java
This PR is intended to add upward compatibility with Picasso 2.71828 in response to issues:
https://github.com/mercadopago/px-android/issues/1925
https://github.com/mercadopago/px-android/issues/1934
=> [enhancement] add Picasso upward compatibility

px-checkout/src/main/res/layout/px_row_pm_search_item.xml
=> [enhancement] add ripple effect to groups items

gradle/deploy_base.gradle
Me traje las mejores del script de deploy de card form
=> Deploy script improvements

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultTracker.java
- Se actualiza el path del touchpoint
=> Update touchpoint path

example/build.gradle, example/src/main/java/com/mercadopago/SampleApplication.java, example/src/main/java/com/mercadopago/android/px/addons/FakeEscManagerBehaviourImpl.java
Necesario para poder probar flujos con ESC en la example app
=> [enhancement] add parcial esc feature example app

example/src/main/java/com/mercadopago/android/px/addons/FakeEscManagerBehaviourImpl.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/model/PaymentRecovery.java
El cambio es necesario para que ya no haya mas relación entre one tap y card vault y poder aislar los flujos de grupos
=> [enhancement] remove card vault dependency from one tap

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/EscPaymentManagerImp.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/InitService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentSettingService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/plugins/PaymentProcessorActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PaymentSettingRepository.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/EscUtil.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/StatusHelper.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/EscPaymentManagerImpTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/util/EscUtilTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/ListUtil.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/Configuration.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/InitResponse.java
Comienza a venir de backend un nodo de configuración donde se indica la lista de status details que estan "blacklisteados" del feature de ESC, por lo que se usa la misma para tomar la decisión de si guardamos o eliminamos el ESC
=> [enhancement] resolve esc blacklisted status as backend configuration

px-checkout/src/main/java/com/mercadopago/android/px/internal/callbacks/PaymentServiceHandler.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/callbacks/PaymentServiceHandlerWrapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethodsPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/plugins/PaymentProcessorActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/model/PaymentRecovery.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/Reason.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/callbacks/PaymentServiceHandlerWrapperTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/PaymentServiceTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenterTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenterTest.java
Se agregan estos cambios para que el reason a la hora de trackear que se entró a la pantalla de cvv sean más específicos y se pueda entender mirando los tracks por que se llegó ahí
=> [ehnancement] improve cvv reason tracking

example/src/main/java/com/mercadopago/android/px/addons/FakeEscManagerBehaviourImpl.java, px-addons/src/main/java/com/mercadopago/android/px/addons/BehaviourProvider.java, px-addons/src/main/java/com/mercadopago/android/px/addons/ESCManagerBehaviour.java, px-addons/src/main/java/com/mercadopago/android/px/addons/internal/ESCManagerDefaultBehaviour.java, px-addons/src/main/java/com/mercadopago/android/px/addons/model/EscDeleteReason.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CardTokenService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/EscPaymentManagerImp.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/TokenizeService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/CardAssociationSession.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodePresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/EscUtil.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/TokenErrorWrapper.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/Reason.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/EscPaymentManagerImpTest.java, px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/PaymentServiceTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/util/TextUtil.java
- Se agrega nueva firma de ESC Manager a PX-Addons
- Se hace uso de la nueva firma para mejorar el tracking en delete
- Se refactoriza el chequeo de error de tokenización
- Se agrega un delete del esc al momento de tokenizar si el reason fue ESC_CAP para empatar los casos de CVV de CAP con los de delete
=> [enhancement] add new esc manager signature

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CardTokenService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodePresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/CardTokenRepository.java, px-checkout/src/test/java/com/mercadopago/android/px/securitycode/SecurityCodePresenterTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/services/GatewayService.java
Se necesita este cambio para que al pedirle al usuario que ingrese CVV debido a que detectamos que se va a pasar del CAP de ESC, hagamos un reset de dicho CAP para que no falle luego en payments
=> [enhancement] call clear cap service when tokenize after esc cap

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/AlternativePayerPaymentMethod.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/Installment.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/PayerPaymentMethodRejected.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/RemediesBody.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/RemediesResponse.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/model/remedies/SuggestionPaymentMethod.kt
Feature remedies
Se agrega modelo para la api de remedies
=> [Feature] Add remedies model

px-checkout/build.gradle, px-checkout/src/main/java/com/mercadopago/android/px/internal/extensions/BaseExtensions.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/CVVRecoveryWrapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/TokenCreationWrapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/model/exceptions/MercadoPagoErrorWrapper.kt, px-checkout/src/test/java/com/mercadopago/android/px/internal/util/TokenCreationWrapperTest.kt
Se busca desacoplar la lógica de tokenizar con un nuevo CVV de la pantalla de CVV.
=> Added Cvv recovery wrapper

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/PaymentRewardMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/PaymentRewardViewModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultBody.java, px-services/src/main/java/com/mercadopago/android/px/model/Behaviour.java, px-services/src/main/java/com/mercadopago/android/px/model/CustomSearchItem.java, px-services/src/main/java/com/mercadopago/android/px/model/ExpressMetadata.java, px-services/src/main/java/com/mercadopago/android/px/model/SliderDisplayInfo.java, px-services/src/main/java/com/mercadopago/android/px/model/StatusMetadata.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/Action.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/InitResponse.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/Modal.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/PaymentReward.java
Se agrega modelo del feature de IFPE
=> [feature] IFPE model

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/AddNewCardOldPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OtherPaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OtherPaymentMethodPresenter.java
Faltaba setear el session_id para los tracks en el alta de tarjeta.
Se agrega el session_id.
=> [FIX] Session_id is added

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
Card form reemplaza el fragment de one tap, dejando la vista de pay button asociado a una vista que no corresponde
Al reemplazar one tap se llama onDestroyView, que es donde deberiamos remover el fragment de pay button y no en on destroy. Este evento se llama al ser reemplazado o al ser destruido
Se mejora la lógica de cuando se registra o se limpia el fragmentLifecycleCallbacks, ya que se estaba registrando dos o mas veces al volver de card form.
Se agrega llamada a super en viewCreated de one tap
=> [fix] pay button disappear

px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/LinkableTextView.java, px-services/src/main/java/com/mercadopago/android/px/model/display_info/LinkablePhrase.java, px-services/src/main/java/com/mercadopago/android/px/model/display_info/LinkableText.java
El objetivo es no depender de lo que venga de backend y ser mas null safe.
=> [fix] make linkable text view null safe

px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-services/src/main/java/com/mercadopago/android/px/model/display_info/DisplayInfo.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/Text.java
Se agrega llenado de la vista payment method description
=> [feature] payment method statement

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethodsFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-checkout/src/main/res/layout/px_fragment_offline_methods.xml, px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
=> [feature] offline methods ifpe texts

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethodsFragment.java
- Changed onPaymentFinished callback from CheckoutActivity to ExpressPaymentFragment
- Changed FragmentManager used to check if is exploding
=> [fix] offline fragment payment finished

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CongratsRepositoryImpl.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PayerComplianceRepositoryImpl.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/ConfigurationModule.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PayerComplianceRepository.kt, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenterTest.java, px-services/src/main/java/com/mercadopago/android/px/internal/services/CongratsService.java
- Handled when payer turned compliant
=> [feature] kyc callback

px-checkout/src/main/java/com/mercadopago/android/px/internal/base/BasePresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/extensions/BaseExtensions.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethodsPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/ActionTypeWrapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/Actionable.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/FromModalToGenericDialogItem.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialog.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialogAction.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialogItem.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialogState.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialogViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/ViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackingContract.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/EventTracker.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/GenericDialogActionEvent.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/GenericDialogDismissEvent.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/GenericDialogOpenEvent.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/KnowYourCustomerFlowEvent.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ViewReceiptEvent.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/GenericDialogTrackData.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/OfflineMethodsViewTracker.java, px-checkout/src/main/res/layout/px_dialog_generic.xml
The following tracks were added:
- (event) /px_checkout/review/one_tap/offline_methods/start_kyc_flow
- (event) /px_checkout/dialog/open { description: String, actions: Int }
- (event) /px_checkout/dialog/dismiss { description: String, actions: Int }
- (event) /px_checkout/dialog/action { description: String, actions: Int, type: String["main_action", "secondary_action"], deepLink: String }
- (event) /px_checkout/result/%s/tap_view_receipt
=> [feature] ifpe tracking

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/PayerComplianceWrapper.kt
Added new control on callback to check old and new compliance status to turn the payer IFPE compliant
=> [feature] turn payer ifpe compliant

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/AddNewCard.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OtherPaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OtherPaymentMethodPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/ActionTypeWrapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/CardFormWithFragmentWrapper.kt, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenterTest.java
Added handling of add new card custom action, one of the custom actions from generic dialogs
=> [feature] add new card custom action handling

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethods.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OfflineMethodsFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/add_new_card/OtherPaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/AccountMoneyFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/AmountDescriptorView.java, px-checkout/src/main/res/layout/px_view_amount_descriptor.xml
Refactor de fragment de OtherPaymentMethodFragment y Accessibility.
=> refactor accessibility and OtherPaymentMethods

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/GenericDialog.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/SpannableFormatter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/MPTextView.java, px-services/src/main/java/com/mercadopago/android/px/model/ExpressMetadata.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/Modal.kt
- Added safe color parse
- Added check of empty when Picasso load an url
- Removed no longer needed serialization names
=> [enhancement] add safe checks for parse color and picasso

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/ConfirmButtonViewModelMapper.java
- HOTFIX - Pay button enable in pure offline method node
=> [release] 4.40.1

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CongratsRepositoryImpl.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
Se filtran los medios de pagos deshabilitados, se elimina cache para remedies.
=> [Feature] Filter disable methods

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmActivity.java
=> [fix] empty view on review and confirm screen

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/mappers/PaymentResultRemediesModelMapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/RemedyTrackData.kt, px-services/src/main/java/com/mercadopago/android/px/model/internal/remedies/RemediesResponse.kt
Ahora la data del extra info para silver bullet viene de backend
=> [Enhancement] Remedy silver bullet extra info from backend

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java
Después de los remedies mostrábamos siempre la congrats genérica
=> [Fix] Business result after remedy

example/src/main/res/values/no-translatable.xml, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/CongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/CongratsViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultBody.java, px-checkout/src/main/res/layout/px_payment_result_body_custom_order.xml, px-services/src/main/java/com/mercadopago/android/px/model/internal/CongratsResponse.java
=> [feature] alternative order for payment result body

CHANGELOG.md, gradle.properties
Se actualiza CFTFormatter para dar soporte a CFTNA.
=> [Release] Update PX to 4.48.1

CHANGELOG.md, gradle.properties
=> [Release] Update version and changelog PX

CHANGELOG.md, gradle.properties
* FEATURE - Money split view in congrats
* ENHANCEMENT - Remedies tracking changes
=> [Release] 4.50.0

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsCurrency.java
Se agrega la clase PaymentCongrats, básica para las nuevas congrats
La idea con esta clase es poder disponibilizar el uso de congrats sin un flujo de checkout
Se agrega la nueva clase, con su builder correspondiente y parcelable
https://docs.google.com/document/d/1eFICVraN3nTxjkPiqOgH2URz3Vnk66mr-cJ__9NnN1U/edit
=> Add PaymentCongrats

px-services/src/main/java/com/mercadopago/android/px/model/internal/PaymentInfo.java
Se crea el objeto PaymentInfo que contiene la info relacionada al pago
Este objeto agrupa info del pago necesaria para mostrar una congrats como el raw amount o el nombre del método de pago
Se crea el objeto PaymentInfo con 4 campos y un builder para su creación. El mismo implemente Parcelable ya que va a estar contenido dentro de PaymentCongrats que tb implementa parcelable.
=> Create PaymentInfo for PaymentCongrats

CHANGELOG.md, gradle.properties
Update PX version to 4.52.0
* ENHANCEMENT - Better discount info.
* FIX - Crash tracking fix by concurrency.
* FIX - Friction track fixed to accept a nullable card object.
* FIX - Fix bad parcelable in payment processor mapper.
=> [Release] Update PX version

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentInfo.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponse.java
Se agrega dto con la info del pago al PaymentCongratsModel
=> Adding payment info to PaymentCongratsModel

px-checkout/src/main/res/layout/px_business_components.xml
Se cambia property `cardPreventCornerOverlap` del componente de` split-money `a `false`
=> [Improvement] Change cardPreventCornerOverlap property

gradle.properties
=> [enhancement] enable R8 fullmode in testapp

example/build.gradle, px-addons/build.gradle, px-checkout/build.gradle, px-services/build.gradle, px-testlib/build.gradle, testlib/build.gradle
=> Added debugProduction build type

CHANGELOG.md, gradle.properties
Release
Se actualiza la versión de PX
=> [Release] Update px version and changelog

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/CongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/MLBusinessMapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponse.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentInfo.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java
Se incorporan los cambios de nombre y otras cosas para tener la misma firma con iOS
=> [PaymentCongrats]Unifying API with iOS 

example/src/main/java/com/mercadopago/CheckoutExampleActivity.java, example/src/main/res/layout/activity_checkout_example.xml, example/src/main/res/values/strings.xml, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/CongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/CongratsViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/MLBusinessMapper.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponse.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsText.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentInfo.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentResultInfo.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/mappers/PaymentResultBodyModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/MPTextView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultAmount.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultBody.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/PaymentResultType.java, px-checkout/src/main/res/layout/px_payment_result_body.xml, px-checkout/src/main/res/layout/px_payment_result_body_custom_order.xml
se actualiza Payment Congrats con los ultimos cambios de master
=> PaymentCongrats Rebase

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/dummy_result/DummyResultPresenter.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/FromPaymentCongratsDiscountItemToItemId.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PXPaymentCongratsTracking.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsResponseMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentInfo.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/PaymentDataHelper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ResultViewTrackModel.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.kt
Se arregla el tracking de la congrats en base al nuevo flujo de congrats
=> Fixing tracking in new congrats

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PXPaymentCongratsTracking.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java
Se arreglan errores de NullPointerException sobre los datos agreados para el tracking
=> Fixing NPE on tracking data

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultPresenter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java
Se agrega el soporte necesario para el autoReturn agregado por necesidad de PX.
=> [PaymentCongrats] Added autoReturn support

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java
Se agrega el seteo del customSorting en el mapper
=> [PaymentCongrats] Adding custon sorting

px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PXPaymentCongratsTracking.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java
Se agrega sessionId, flow y flowExtraInfo a los datos de trackeo
=> Se agrega sessionId, flow y flowExtraInfo a los datos de trackeo

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonState.kt
FIX - Message for Snackbar is null.
=> [Release] Update PX to 4.57.1

px-checkout/src/main/java/com/mercadopago/android/px/internal/extensions/ImageViewExtensions.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/offline_methods/FromOfflinePaymentTypesMetadataToOfflineItems.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/offline_methods/OfflineMethodItem.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/offline_methods/OfflineMethodsRowHolder.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/mappers/PaymentResultBodyModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/ElementDescriptorView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-checkout/src/main/res/drawable/px_generic_method.xml, px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentMethod.java, px-services/src/main/java/com/mercadopago/android/px/model/internal/CongratsResponse.java
=> [feature] pm assets from odr

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultMethod.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.kt
Segundo PR con los fixes requeridos por el codeReview sobre "new-payment-congrats"
=> [PaymentCongrats] Second codereview fixes

example/src/main/java/com/mercadopago/android/px/feature/payment_congrats/PaymentCongratsMock.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PXPaymentCongratsTracking.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ResultViewTrackModel.java
Se incorpora el atributo PaymentMethodTypeId en PXPaymentCongratsTracking
=> [PaymentCongrats] Adding PaymentMethodTypeId on PXPaymentCongratsTracking

px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java
Se agrega el mapeo del discount en el PaymentCongratsModelMapper
=> Fixing missing discount mapping

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/InitService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentSettingService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/explode/ExplodingFragment.java
- Fixed persistent data from advanced configuration.
- Fixed clean refresh after new card when restoring session.
=> [Fix] Persistent data from advanced configuration

CHANGELOG.md, gradle.properties
* FEATURE - New security code screen.
* FEATURE - Add synced android id getter in esc behaviour.
* ENHANCEMENT - Throw error screen instead of exception in one tap.
* FIX - Persistent data from advanced configuration.
* FIX - Clean refresh after new card flow with recovered session.
=> [Release] 4.61.0

CHANGELOG.md, gradle.properties
* FEATURE - Dynamic discounts params
* FIX - Wrong payment status code in result track
* FIX - Changed preference amount field track to total amount
=> [Release] 4.62.0

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PXPaymentCongratsTracking.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackingHelper.java, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/PaymentDataExtraInfo.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ResultViewTrackModel.java
* FIX - Restored congrats methods signature that caused crashes for other teams.
* FIX - Payment data extra info on result track.
=> [Release] 4.62.1

CHANGELOG.md, gradle.properties
* FEATURE - Installments v2 experiment.
* FEATURE - Improved congrats auto return experience.
* ENHANCEMENT - Added experiment seed getter into tracking behaviour.
* FIX - Prevent pay button to be enabled without a usable slider option.
* FIX - Incorrectly tracking Business congrats on view stop.
* FIX - Added last four digits to token when esc is disabled.
=> [Release] 4.63.0

CHANGELOG.md, gradle.properties
* FEATURE - Added support to cards without cvv.
* ENHANCEMENT - Added location granted status in congrats endpoint.
=> [Release] 4.64.0

CHANGELOG.md, gradle.properties
* FEATURE - Appending params to back_url and redirect_url
=> [Release] 4.65.0

CHANGELOG.md
* FEATURE - Added Loyalty Broadcaster in Payment Congrats
* ENHANCEMENT - Added Discount Center track factory
* FIX - Added missing "remedies" to business congrats error track
* FIX - Security code reason track
=> [Release] 4.66.0

CHANGELOG.md, gradle.properties
* ENHANCEMENT - Removed old checkout flow.
=> [Release] 4.67.0

CHANGELOG.md, gradle.properties
* FIX - Removed remedies api call with business payments
=> [Release] 4.67.1

CHANGELOG.md, gradle.properties
* ENHANCEMENT - Added merchantOrderId to congrats api call
* FEATURE - Added WebPay flow for debit card in Chile.
=> [Release] Update lib version and changelog

CHANGELOG.md, gradle.properties
* FEATURE - Card Drawer for AM
* FEATURE - Card tap modal behaviour
* FIX - ViewPager height zero in some extreme cases
=> [Release] 4.69.0

CHANGELOG.md, gradle.properties
* FEATURE - Generate jacoco coverage report
* ENHANCEMENT - Migrated to Gradle 6.6
* FIX - Fix session clear in prefetch service
* FIX - Avoiding exploding fragment context crash
=> [Release] 4.70.0

gradle.properties, gradle/base_android_lib.gradle, gradle/wrapper/gradle-wrapper.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/TermsAndConditionsActivity.java, px-checkout/src/main/res/layout/px_experiment_arrow_default.xml, px-checkout/src/main/res/layout/px_other_payment_method_card_view_large_low_res.xml, px-checkout/src/main/res/layout/px_other_payment_method_card_view_small.xml, px-checkout/src/main/res/layout/px_other_payment_method_card_view_small_low_res.xml, px-checkout/src/main/res/layout/px_payment_result_method_icon.xml
No subo a la 4.1.1 como la wallet porque se rompe Jacoco, acá está el issue:
https://issuetracker.google.com/issues/171125857
=> [Enhancement] Updates Gradle to 6.7.1 and AGP to 4.0.1

CHANGELOG.md, gradle.properties
* ENHANCEMENT - Migrated to Gradle 6.7.1 and AGP 4.0.1.
* ENHANCEMENT - Deprecated locale behaviour.
* ENHANCEMENT - Deprecated init cache in favor of separated repositories.
* ENHANCEMENT - Removed deprecated validators from the testlib.
* ENHANCEMENT - Tracker dependency injection.
=> [Release] 4.71.0

px-checkout/src/main/java/com/mercadopago/android/px/core/DynamicFragmentCreator.java, px-checkout/src/main/java/com/mercadopago/android/px/core/SplitPaymentProcessor.java
Se agrega field `validation_program_id` en checkout data.
=> [Feature] Validation program id added on CheckoutData

CHANGELOG.md, gradle.properties
* ENHANCEMENT - Added validation program id to checkout data.
=> [Release] 4.72.0

CHANGELOG.md, gradle.properties
* FIX - Crash tracking session halted.
=> [Release] 4.72.1

CHANGELOG.md, gradle.properties
=> [Release] 4.73.0

px-addons/build.gradle, px-addons/src/main/java/com/mercadopago/android/px/addons/BehaviourProvider.java, px-addons/src/main/java/com/mercadopago/android/px/addons/PXBehaviourConfigurer.java, px-addons/src/main/java/com/mercadopago/android/px/addons/ThreeDSBehaviour.kt, px-addons/src/main/java/com/mercadopago/android/px/addons/internal/ThreeDSDefaultBehaviour.kt, px-addons/src/main/java/com/mercadopago/android/px/addons/model/ThreeDSDataOnlyParams.kt, px-addons/src/test/java/com/mercadopago/android/px/addons/ThreeDSDefaultBehaviourTest.kt, px-addons/src/test/java/com/mercadopago/android/px/addons/validator/internal/SecurityValidatorTest.kt
=> [Feature] ThreeDSBehaviour added

CHANGELOG.md, gradle.properties
* FEATURE - ThreeDSBehaviour added
=> [Release] Update PX version to 4.74.0

px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/OneTapItemToDisabledPaymentMethodMapper.kt, px-checkout/src/test/java/com/mercadopago/android/px/internal/mapper/OneTapItemToDisabledPaymentMethodMapperTest.kt
=> [Fix] Leave offline method mapping as a payment method disabled

CHANGELOG.md, gradle.properties
=> [Release] 4.78.0

px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
Hoy hay dos tipos de retry en el proceso para refrescar el checkout luego de un alta de tarjeta
el retry porque la tarjeta todavia no la devuelve card (es decir que el usuario todavia no la podria usar) y el retry cuando la card ya viene pero  viene con un flag de reintentar (este flag de reintentar podria tener varios motivos pero por ahora el unico es que no cumple con un validation program por el estado de tokenizacion).
Por ahora el delay era de 500ms, pero para el segundo tipo de retry, el proceso asincronico de tokenizar la tarjeta que sucede independienemente de nuestro flujo podria llevar mas de 5 segundos en finalizarse, por lo cual establecemos un delay mas largo solo para estos casos de hasta 5000ms.
=> [enhancement] add long retry delay

CHANGELOG.md, gradle.properties
* FIX - Applications track collided with Melidata application.
* FIX - Audio player crash when api call failed.
* ENHANCEMENT - Added long retry for special cases.
=> [Release] 4.79.0

example/build.gradle
=> fix for enable xjvm default

CHANGELOG.md, gradle.properties
Reverts mercadopago/px-android#2567
=> Revert "[Release] 4.91.0"

CHANGELOG.md, gradle.properties
* FIX - Payment result screen fixed
=> [Release] 4.96.1

CHANGELOG.md, gradle.properties
* FEATURE - Debin support added.
* ENHANCEMENT - Track for post payment flow added.
=> [Release] 4.103.0

CHANGELOG.md, gradle.properties
* FIX - T&C selection fixed when changing installments for consumer credits.
* ENHANCEMENT - Added tests for debin changes.
=> [Release] 4.104.0

px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultHeader.java
=> fix: validate badgeImage resource when is 0

px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultHeader.java
Reverts mercadopago/px-android#2652
=> Revert "fix: validate badgeImage resource when is 0"

CHANGELOG.md, gradle.properties, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultHeader.java
* FIX - Crash when badge placeholder is 0.
=> [Release] 4.103.1

CHANGELOG.md, gradle.properties
* FIX - Crash when badge placeholder is 0.
=> [Release] 4.104.1

CHANGELOG.md, gradle.properties
* FEATURE - New wordings for IFPE regulation.
=> [Release] 4.105.0

CHANGELOG.md, gradle.properties
* FIX - Removed total duplicate when payment method is debit card.
* FIX - Call to action when payment method is debin.
* FIX - Crash payment method not found.
=> [Release] 4.106.0

CHANGELOG.md, gradle.properties
* FIX - Congrats empty texts when paying with account money
* FIX - Duplicated payments in some cases where pay button was being enabled incorrectly.
* FIX - Adjust track offline_methods.
=> [Release] 4.107.0

CHANGELOG.md, gradle.properties
* FIX - CheckoutActivity launch mode changed to clean activity correctly.
* FIX - Parameter specified as non-null is null - solution: avoid to clear session with a new method
=> [Release] 4.108.1

CHANGELOG.md, gradle.properties
- FIX - Parameter specified as non-null is null - parameter state
- FIX - Crash when PaymentTypeId is null
- FEATURE - Remove label "interest free" from the front of the installment amount
- FEATURE - Added tracks for debin transfer.
=> [Release] Update version to 4.109.0

CHANGELOG.md, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/OneTapItemRepositoryImpl.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/UserSelectionService.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsDeepLinkActivity.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsResult.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsViewModel.kt, px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/FrictionEventTracker.kt, px-checkout/src/test/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsViewModelTest.kt
Add runCatching to handle errors when calling `createPaymentResult` on `PaymentRepository`
[PXN-3576](https://mercadolibre.atlassian.net/browse/PXN-3576)
Conclusion: The crash is generated when the preference is not cleared and trying to search in a list that does not contain data, this fix was previously solved by keeping the session in the [PR 2682](https://github.com/mercadopago/px-android/pull/2682).
This new PR solves possible crashes in the flow and eliminates the preference when clean up the session, thus preventing a customOptionId from arriving with a different value.
For semovi flow the integrator was opening our congrats and in some cases the `customOptionId` has an invalid value, because the sharedPreference is returning null and by default the  `customOptionId` is empty
using …
=> [Fix]: PXN-3576 - Handler error when customOptionId is invalid

CHANGELOG.md, gradle.properties
* FIX - Crash when installments of payerCosts for credit cards is null.
* ENHANCEMENT - Summary header logic refactor
* ENHANCEMENT - Errors are handled in postPaymentFlow
=> [Release] 4.110.0

gradle.properties, px-addons/src/main/java/com/mercadopago/android/px/addons/TokenDeviceBehaviour.kt, px-addons/src/main/java/com/mercadopago/android/px/addons/internal/TokenDeviceDefaultBehaviour.kt, px-addons/src/main/java/com/mercadopago/android/px/addons/tokenization/Tokenize.kt, px-addons/src/main/java/com/mercadopago/android/px/addons/tracking/Tracker.kt
Update tokenization contract for CTF compatibility
We have some more parameters for when the enrollment flow is for CTF/Visa. We are adding them as needed!
=> [PXN-3420] update tokenization contract for CTF compatibility

CHANGELOG.md, gradle.properties
* FEATURE - New layout consumer credits and new tag.
* FEATURE - Adjust tag card consumer credits with size medium.
* FEATURE - New background consumer credits.
=> [Release] 4.111.0

CHANGELOG.md, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/offline_methods/OfflineMethodsFragment.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/offline_methods/OfflineMethodsRowHolder.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/SplitPaymentHeaderAdapter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/AmountLabeledFormatter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/InterestFormatter.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/PayerCostFormatter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/SpannableFormatter.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/Badge.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/LinkableTextView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/MPTextView.kt, px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodDescriptorView.java, px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/CreditCardDescriptorModel.java, px-checkout/src/test/java/com/mercadopago/android/px/format/InterestRateFormatterTest.kt
Migración de utils de px-checkout a utils de px-core.
Improvement day.
Empezamos a migrar algunos utils para usar los utils de core.
=> Migration of some utils methods to use utils from core

CHANGELOG.md, gradle.properties
* FEATURE - Added view binding for OneTapFragment.
* FEATURE - PX as payment method selector.
=> [Release] 4.112.0

CHANGELOG.md, gradle.properties
* FEATURE - New pending screen to debin status detail.
* FEATURE - Custom behavior to support custom texts in payment methods.
* FEATURE - Rules configuration is supported to apply in the means of payment.
* ENHANCEMENT - New checkout type on tracker added
=> [Release] 4.114.0
