- sdk/src/androidTest/java/com/mercadopago/CheckoutActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/InstructionsActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/test/FakeAPI.java
- sdk/src/androidTest/java/com/mercadopago/test/FakeInterceptor.java
- sdk/src/androidTest/java/com/mercadopago/test/rules/MockedApiTestRule.java
- sdk/src/main/java/com/mercadopago/CheckoutActivity.java
- sdk/src/main/res/layout/mpsdk_content_checkout.xml
Se corrige el problema de que no corrían todos los tests juntos (sí por separado).
¿Qué pasaba? Para mockear la api estoy agregando un Interceptor, que tenía una lista de respuestas, que iban cambiando según el test. OkHttp internamente utiliza el método
Util.immutableList(builder.interceptors);
Por lo que la lista de interceptors cambia, y aunque agregue respuestas en la original no se modifica la actual.
Para evitar esto, un workaround fue crear una clase FakeAPI que contenga las respuestas, y el interceptor acceda a ellas estáticamente.
> Fixed mocked api framework

- sdk/src/androidTest/java/com/mercadopago/CheckoutActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/InstructionsActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/PaymentVaultActivityTest.java
- sdk/src/main/AndroidManifest.xml
- sdk/src/main/java/com/mercadopago/BankDealsActivity.java
- sdk/src/main/java/com/mercadopago/CheckoutActivity.java
- sdk/src/main/java/com/mercadopago/CustomerCardsActivity.java
- sdk/src/main/java/com/mercadopago/ErrorActivity.java
- sdk/src/main/java/com/mercadopago/FrontCardActivity.java
- sdk/src/main/java/com/mercadopago/InstructionsActivity.java
- sdk/src/main/java/com/mercadopago/MercadoPagoActivity.java
- sdk/src/main/java/com/mercadopago/PaymentMethodsActivity.java
- sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java
- sdk/src/main/java/com/mercadopago/TermsAndConditionsActivity.java
- sdk/src/main/java/com/mercadopago/adapters/CustomerCardsAdapter.java
- sdk/src/main/java/com/mercadopago/core/MercadoPago.java
- sdk/src/main/res/values/dimens.xml
@valeserber @MatiasRomar @matiasgualino Les pido si pueden ver bien en detalle este PR, y vean si tienen alguna idea o feedback para sumar a esto. 
La intención es que todas las Activities de la SDK hereden de esta clase abstracta, así que les cuento un poco qué ganaríamos. Se usa en esta branch en PaymentMethodsActivity, PaymentVaultActivity, CheckoutActivity, InstructionsActivity, TermsAndConditionsActivity y BankDealsActivity.
**Responsabilidades que toma MercadoPagoActivity:**
- Conocimiento de si una Activity está activa: hasta ahora tenemos un flag en cada Activity "mActiveActivity", y lo seteamos en los métodos onResume, onPause, etc de c/u. Ahora sólo se hace en MercadoPagoActivity, que cuenta con un método **isActivityActive()**.
- Manejo de recupero de errores: actualmente …
> Creación clase MercadoPagoActivity

- sdk/src/main/java/com/mercadopago/CardVaultActivity.java
- sdk/src/main/java/com/mercadopago/FrontCardActivity.java
- sdk/src/main/java/com/mercadopago/GuessingCardActivity.java
- sdk/src/main/java/com/mercadopago/InstallmentsActivity.java
- sdk/src/main/java/com/mercadopago/IssuersActivity.java
- sdk/src/main/java/com/mercadopago/MercadoPagoActivity.java
- sdk/src/main/java/com/mercadopago/ShowCardActivity.java
- GuessingCardActivity, CardVaultActivity, InstallmentsActivity & IssuersActivity, ahora extienden indirectamente de MercadoPagoActivity.
- Se agregó el método initializeFragments en MercadoPagoActivity, dentro del OnCreate, para que lo implementen las subclases que deseen.
> Refactor guessing con MercadoPagoActivity

- sdk/src/androidTest/java/com/mercadopago/model/PaymentMethodSearchGetPaymentMethodTest.java
- sdk/src/main/java/com/mercadopago/model/PaymentMethodSearch.java
Se refactorizó la forma en que se obtiene el PaymentMethod correspondiente con el PaymentTypeId que se incluye en el  id del item, dado un PaymentMethodSearchItem que el usuario selecciona.
También el método que dado un medio de pago, obtiene el item correspondiente del los que se encuentran en la respuesta del servicio. 
De la nueva forma, no dependemos de cómo se separe en backend el id del medio de pago, del del tipo de medio de pago:
"bancomer_bank_transfer" o bancomer.bank_transfer" funcionan.
Se modificaron los test cases correspondientes.
A su vez, se emprolijó el código.
> PaymentMethodSearch refactor

- sdk/src/androidTest/java/com/mercadopago/BankDealsActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/TermsAndConditionsActivityTest.java
- sdk/src/main/java/com/mercadopago/BankDealsActivity.java
- sdk/src/main/java/com/mercadopago/TermsAndConditionsActivity.java
Cobertura de líneas: 99%
Cobertura de branches:  92%
Se cambió la key con la cual se envían los terminos y condiciones de las promociones  de "termsAndConditions" por "bankDealLegals", porque esta pantalla se encarga también de los términos y condiciones de MercadoPago y quedaba confuso.
> Se agregan tests de TermsAndConditionsActivity

- sdk/src/main/res/anim/mpsdk_hold.xml
Animación que afectaba al seleccionar un banco, ahora es más rápida porque antes parecía "colgarse".
> Reduje el tiempo del hold de animación

- sdk/src/androidTest/java/com/mercadopago/GuessingCardActivityTest.java
- sdk/src/main/java/com/mercadopago/CardVaultActivity.java
- sdk/src/main/java/com/mercadopago/GuessingCardActivity.java
- Había un bug permitía hacer foco en el código de seguridad en un momento que no era adecuado. Pasaba cuando ingresabas un número de tarjeta que no tiene código de seguridad requerido, avanzabas hasta el número de documento, luego volvías a cambiar el número de tarjeta por uno con código de seguridad requerido y luego avanzabas hacia el código de seguridad.
- Agregué el test que valida este caso de uso
- Agregué validación de CardVault que faltaba para los installments activados
> Fix bug código de seguridad

- sdk/src/androidTest/java/com/mercadopago/BankDealsActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/GuessingCardActivityTest.java
- sdk/src/main/java/com/mercadopago/BankDealsActivity.java
- sdk/src/main/java/com/mercadopago/GuessingCardActivity.java
- sdk/src/main/java/com/mercadopago/core/MercadoPago.java
- Se agrega llamada a la API en GuessingCardActivity para saber si hay promociones, y si no las hay no se muestra el texto en "Ver Promociones" en Toolbar.
- Se agrega que se pueda enviar una lista de Bank Deals a la pantalla de Bank Deals para evitar la doble llamada a la API
- Se agregan tests en GuessingCardActivityTest y en BankDealsActivityTest para validar casos de uso con lista de bank deals vacía y no vacía
> Agregué chequeo para mostrar promos

- sdk/src/androidTest/assets/mocks/identification_type_cnpj.json
- sdk/src/androidTest/assets/mocks/identification_type_cpf.json
- sdk/src/androidTest/java/com/mercadopago/GuessingCardActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/model/DummyIdentificationType.java
- sdk/src/androidTest/java/com/mercadopago/test/StaticMock.java
- sdk/src/androidTest/java/com/mercadopago/utils/IdentificationTestUtils.java
- sdk/src/main/java/com/mercadopago/CardInterface.java
- sdk/src/main/java/com/mercadopago/CardVaultActivity.java
- sdk/src/main/java/com/mercadopago/FrontCardActivity.java
- sdk/src/main/java/com/mercadopago/GuessingCardActivity.java
- sdk/src/main/java/com/mercadopago/InstallmentsActivity.java
- sdk/src/main/java/com/mercadopago/IssuersActivity.java
- sdk/src/main/java/com/mercadopago/fragments/CardFrontFragment.java
- sdk/src/main/java/com/mercadopago/fragments/CardIdentificationFragment.java
- sdk/src/main/java/com/mercadopago/util/MPCardMaskUtil.java
- sdk/src/main/java/com/mercadopago/util/MPMaskUtil.java
- Se agrega la máscara para CPF y CNPJ 
- Se agrega una clase MPMaskUtil donde se agrupa las máscaras de identificación y de los números de tarjeta
- Se agregan tests para validar las máscaras de DNI, CPF y CNPJ
> Máscara de identification number para CPF y CNPJ

- sdk/src/main/java/com/mercadopago/CardVaultActivity.java
- sdk/src/main/java/com/mercadopago/model/ApiException.java
- sdk/src/main/java/com/mercadopago/uicontrollers/paymentmethodsearch/PaymentMethodSearchSmallRow.java
Cuando no hay cuotas, no es requerido para el usuario envíar el Site. El trackeo del "back" hace site.getId(), lo que daba como resultado un NullPointerException cuando no estaba seteado.
> Fix en "back" desde CardVaultActivity sin cuotas

- example/build.gradle
- sdk/build.gradle
- sdk/src/main/java/com/mercadopago/services/PaymentService.java
Se cambian desde la sección "Build variants":
Para ir a beta, seleccionar un build variant con prefijo "dev": devDebug durante el desarrollo.
Para ir a v1, con prefijo "prod": prodDebug durante el desarrollo.
> Se agregaron build variants para consumir API beta en desarrollo

- sdk/src/androidTest/java/com/mercadopago/InstructionsActivityTest.java
- sdk/src/main/java/com/mercadopago/InstructionsActivity.java
- sdk/src/main/java/com/mercadopago/PaymentResultActivity.java
- sdk/src/main/java/com/mercadopago/core/MercadoPago.java
Se modificó la InstructionActivity. Antes se iniciaba con un payment, una publicKey y un paymentMethod. Ahora se inicia con un payment, una publicKey y un paymentTypeId. 
Solo utilizábamos el paymentTypeId del paymentMethod y además de esta forma estamos alineados con el SDK de IOS.
> Refactor Instrucciones

- build.gradle
- example/build.gradle
- sdk/build.gradle
- sdk/src/androidTest/java/com/mercadopago/GuessingCardActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/IssuersActivityTest.java
- sdk/src/androidTest/java/com/mercadopago/test/StaticMock.java
- sdk/src/main/java/com/mercadopago/FrontCardActivity.java
- sdk/src/main/java/com/mercadopago/GuessingCardActivity.java
- sdk/src/main/java/com/mercadopago/fragments/CardFrontFragment.java
- GuessingCardActivity now stores in bundle all the variables and fragments it uses, so that when the OS destroys the app, and then the user comes back to it, its state is restored and the app doesn't crash.
- Stores FrontFragment, BackFragment, IdentificationFragment, and all the variables it needs.
- This was tested using the emulator, activating the developer option: "Don't keep activities (destroy every activity as soon as the user leaves it)".
- Added tests that recreate the activity.
- [Video](https://drive.google.com/open?id=0B7v04H2J8VPCVEpUd2NWRmlwVzg
)
- Coverage of GuessingCardActivity is 90% instructions, 63% branches
- Added tests for methods *onSaveInstanceState* (100% instructions, 67% branches), and for *onRestoreInstanceState* (100% instructions, 50% …
> Fix crash when restoring app 

- sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java
Se evita enviar el email al servicio de medios de pago del wrapper para que no aparezcan tarjetas guardadas en el flujo completo, si existieran, ya que no puede finalizarse el pago porque no contamos con el customer id (Para el caso de integración con Payment Result).
**Pruebas:**
- Ver tarjetas agregando servidor del merchant a ServicePreference.
- Ver tarjetas del Usuario agregando el AT (Integración tipo Wallet, con PaymentData).
- Caso sin AT ni ServicePreference (No deberían verse tarjetas).
> [Fix] Avoid sending email to groups service

- sdk/src/main/java/com/mercadopago/constants/PaymentMethods.java
Se agregaron constantes de métodos de pago por país según la próxima release que incluirá rollouts. Cambios:
* Constantes para: MPE, MCO, MLC, MLV.
* Sólo tarjetas para: MLC, MLV.
El caso de uso es el de las exclusiones de medios de pago, se puede realizar por ejemplo:
```
return new CheckoutPreference.Builder()
.addItem(new Item("Item",new BigDecimal(10000)))
.setSite(Sites.PERU)
.addExcludedPaymentMethod(PaymentMethods.PERU.PAGOEFECTIVO_ATM)
.build();
```
Closes #548
> [Feature] Constantes de PaymentMethods

- sdk/src/main/java/com/mercadopago/SecurityCodeActivity.java
- sdk/src/main/java/com/mercadopago/presenters/SecurityCodePresenter.java
- sdk/src/main/java/com/mercadopago/providers/SecurityCodeProvider.java
- sdk/src/main/java/com/mercadopago/providers/SecurityCodeProviderImpl.java
- sdk/src/main/java/com/mercadopago/views/SecurityCodeActivityView.java
- sdk/src/test/java/com/mercadopago/securitycode/SecurityCodePresenterTest.java
- En la pantalla de código de seguridad no se estaba mostrando el mensaje de error cuando el usuario quiere continuar habiendo ingresado menos números de los necesarios.
- No se estaba usando el ExceptionHandler que se creó con el refactor a MVP de Guessing, que es quien toma la CardTokenException y la traduce a un mensaje de error.
- Ahora se reciben CardTokenExceptions siempre y se usa ese handler para mostrar los errores.
> [Fix] Error message not being shown in security code activity

- sdk/src/main/java/com/mercadopago/CheckoutActivity.java
- sdk/src/main/java/com/mercadopago/core/MercadoPagoCheckout.java
- sdk/src/main/java/com/mercadopago/preferences/FlowPreference.java
- sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java
- sdk/src/main/java/com/mercadopago/views/CheckoutView.java
- sdk/src/test/java/com/mercadopago/checkout/CheckoutPresenterTest.java
Se permite configurar una salida del Checkout cuando el usuario cambia el medio de pago en RyC o presiona back.
> [Feature] Added inversion of control from RyC

- sdk/src/main/java/com/mercadopago/presenters/CardVaultPresenter.java
//Description
En la app de ejemplo al entrar en "Componentes de UI" / "Cobra con tarjetas sin cuotas" se produce un NullPointerException porque están usando Boolean y es null, se refactorizaron los Booleans por datos primitivos boolean. No hay que usar Boolean excepto que sea necesario aceptar null (y sus consecuencias).
Closes #
CardVaultPresenter
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> [Fix] NullPointerException in example app

- sdk/src/main/java/com/mercadopago/presenters/CheckoutPresenter.java
//Description
Cuando hay solo un medio de pago disponible al hacer back en revisa y confirma vuelve a revisa y confirma con el medio seleccionado, hay que salir del checkout cuando solo hay un medio de pago.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> [bug] Salir de checkout al hacer back en revisa y confirma y solo hay un medio de pago disponible.

- CHANGELOG-v3.md
- README.md
- sdk/build.gradle
Se vuelve atrás el cambio del comando "implements" por "compile".
Se actualiza el README y el CHANGELOG-v3.
> [Fix] Dependencies transitivity

- sdk/src/main/java/com/mercadopago/model/PaymentRecovery.java
- sdk/src/main/java/com/mercadopago/presenters/SecurityCodePresenter.java
- En el caso de Rejected por "card disabled", el botón del footer de "Ya habilité mi tarjeta" estaba tirando un error al tocarlo.
- Se implementó que este botón recupere el pago clonando el token (caso de uso que antes no se hacía con ese status detail)
> [Fix] Recovering payment on card disabled

- sdk/src/main/java/com/mercadopago/paymentresult/components/Body.java
Se muestra el payment_id cuando se paga con plugin. 
**Antes:**
**Después:**
> [Fix] Showed payment id with plugin

- sdk/build.gradle
- sdk/src/main/java/com/mercadopago/BankDealsActivity.java
- sdk/src/main/java/com/mercadopago/CallForAuthorizeActivity.java
- sdk/src/main/java/com/mercadopago/CongratsActivity.java
- sdk/src/main/java/com/mercadopago/ErrorActivity.java
- sdk/src/main/java/com/mercadopago/InstallmentsActivity.java
- sdk/src/main/java/com/mercadopago/InstructionsActivity.java
- sdk/src/main/java/com/mercadopago/IssuersActivity.java
- sdk/src/main/java/com/mercadopago/PaymentTypesActivity.java
- sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java
- sdk/src/main/java/com/mercadopago/PendingActivity.java
- sdk/src/main/java/com/mercadopago/RejectionActivity.java
- sdk/src/main/java/com/mercadopago/ReviewAndConfirmActivity.java
- sdk/src/main/java/com/mercadopago/SecurityCodeActivity.java
- sdk/src/main/java/com/mercadopago/paymentresult/PaymentResultActivity.java
- sdk/src/main/java/com/mercadopago/providers/GuessingCardProviderImpl.java
- sdk/src/main/java/com/mercadopago/tracker/MPTrackingContext.java
//Description
Usamos NoOpStrategy para que px no trackee internamente, si se llaman a los listeners.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> Use NoOpStrategy

- sdk/src/main/java/com/mercadopago/PaymentVaultActivity.java
- sdk/src/main/java/com/mercadopago/plugins/PaymentMethodPluginActivity.java
Se agrega por pedido de InStore el trackeo de la pantalla de plugin. Se acordó hacerlo con el String CONFIG_PAYMENT_METHOD + id_plugin que setean ellos. 
Se puede configurar un TrackListener en CheckoutExampleActivity con un log del nombre de pantalla. Al elegir un plugin como medio de pago (como dinero en cuenta) Se debería loguear como screenName "CONFIG_PAYMENT_METHOD" + id_plugin. 
```
MPTracker.getInstance().setTracksListener(new TracksListener() {
@Override
public void onScreenLaunched(String screenName) {
Log.v("SCREEN_NAME_TRACKED",screenName);
}
@Override
public void onEventPerformed(Map<String, String> event) {
}
});
```
> [Feature] Payment Method Plugin ScreenTracking

- sdk/src/main/java/com/mercadopago/ReviewAndConfirmActivity.java
- sdk/src/main/java/com/mercadopago/core/MercadoPagoComponents.java
- sdk/src/main/java/com/mercadopago/paymentresult/components/PaymentResultContainer.java
- sdk/src/main/java/com/mercadopago/providers/ReviewAndConfirmProviderImpl.java
- sdk/src/main/java/com/mercadopago/uicontrollers/reviewandconfirm/SummaryView.java
//Description
- El setter setApprovedTitle de PaymentResultScreenPreference.Builder no impacta el title en la congrats.
- El setter setConfirmText de ReviewScreenPreference.Builder no funciona.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> [Fix] preferences

- sdk/build.gradle
//Description
Se actualizó la librería de tracking a la version 3.0.2-noop-2
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> Tracking lib update version 3.0.2-noop-2

- example/src/main/java/com/mercadopago/examples/checkout/CheckoutExampleActivity.java
- sdk/src/main/java/com/mercadopago/uicontrollers/reviewandconfirm/ReviewProductView.java
//Description
A separator view was removed from xml layout but had a reference in code, in a particular situation produces NPE.
Closes #
_Note:_
_Note:_
_Note:_
_Note:_
_Note:_
> [Fix] Null view reference

- gradle.properties
- px-checkout/src/main/res/values-es-rAR/strings.xml
Api >=27 cambia la forma de resolver resources por región, generando que en apps es-rAR se observen textos en es-rMX
device Api >=27 - > forzar locale a es AR; entrar al checkout e ir a installments, debe decir cuotas y no mensualidades.
> [hotfix] 4.0.0 beta 34.0.7

- CHANGELOG-v4.md
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/onetap/OneTapFragment.java
Al obtener un resultado de pago "call for authorize" o alguno que permita recuperarse, se volvía a grupos, y luego al hacer back se veía el Fragment de explosión (pintado del color con el que explotó) arriba de one tap.
Se remueve el fragment de explosión al volver a la pantalla de one tap.
Caso 19: call for authorize
> [Fix] Fixed recovery payment case with exploding button in one tap

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/CheckoutActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/CheckoutPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/CheckoutStateModel.java
Con "Eliminar Actividades" activado, estaba crasheando por no tener el CheckoutStateModel.
Se inicializa el CheckoutStateModel si no se puede recuperar.
Caso Business - Complete - Approved
https://medium.com/@trionkidnapper/android-mvp-keeping-presenters-alive-a91b9e080761
> [Fix] Null pointer with kill activities

- CHANGELOG-v4.md
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/PaymentVaultPresenter.java
Crasheaba cuando trackeabamos el paymentMethodSearchItem de grupos obtenido de PaymentMethodSearch y PaymentMethodSearch era nulo.
Ahora, antes de ejecutar el track, se va a buscar a GroupsRepository el PaymentMethodSearch.
> [fix] Fixed PaymentMethodSearch tracking

- example/src/main/java/com/mercadopago/SampleTopFragment.java
- example/src/main/java/com/mercadopago/android/px/internal/features/plugins/SampleDialog.java
- example/src/main/java/com/mercadopago/android/px/utils/ExamplesUtils.java
- example/src/main/res/layout/sample_dialog.xml
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/AdvancedConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/DynamicDialogConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/DynamicFragmentConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/ReviewAndConfirmConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/core/DynamicDialogCreator.java
- px-checkout/src/main/java/com/mercadopago/android/px/core/DynamicFragmentCreator.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirm.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/components/ReviewAndConfirmContainer.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/components/ReviewAndConfirmRenderer.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/util/FragmentUtil.java
- px-checkout/src/main/res/values/ids.xml
PANTALLA INTERMEDIA
• Soporte pantalla custom entre "Selección de medio de pago" y "Revisa y confirma". habilitar o no esta pantalla depende del medio de pago seleccionado.
CUSTOMIZAR RYC POST SELECCION
• Soporte para mostrar u ocultar cajitas de revisa y confirma dependiendo del medio de pago seleccionado.
> [feature] dynamic fragments for screen locations

- px-checkout/src/main/java/com/mercadopago/android/px/configuration/AdvancedConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/CustomStringConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/configuration/DynamicLanguageConfiguration.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/PaymentMethodsActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/providers/PaymentVaultProviderImpl.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/AmountView.java
- px-checkout/src/main/res/values-es/strings.xml
- px-checkout/src/main/res/values-pt/strings.xml
- px-checkout/src/main/res/values/strings.xml
Se agrega la posibilidad de modificar los el verbo principal de la pantalla de medios de pago, pudiendo enviar un String Rrsource Id que contenga el verbo a reemplazar (por ejemplo: "pagar" por "ingresar")
Necesitamos poder modificar los textos de la pantalla de medios de pago
Se spliteó el string resource utilizado para el titulo de la pantalla y tambien el de pie de pantalla (texto de "Total to pay") para que este ultimo verbo sea variable
Luego de iniciar checkout (luego de llamar a startPayment) se debe setear un InternalConfiguration a travez de la Session
- No breaking change
> [Feature] Wording configuration

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultNavigator.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionInteractionComponent.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionInteractionComponentRenderer.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionInteractions.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionInteractionsRenderer.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionsContent.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/components/InstructionsContentRenderer.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/paymentresult/props/InstructionInteractionsProps.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/CopyAction.java
- px-checkout/src/main/res/layout/px_payment_result_instruction_interaction.xml
- px-checkout/src/main/res/layout/px_payment_result_instructions_interactions.xml
- px-checkout/src/main/res/values-es/strings.xml
- px-checkout/src/main/res/values-pt/strings.xml
- px-checkout/src/main/res/values/strings.xml
- px-checkout/src/test/java/com/mercadopago/android/px/internal/features/paymentresult/PaymentResultTest.java
- px-services/src/main/java/com/mercadopago/android/px/model/Instruction.java
- px-services/src/main/java/com/mercadopago/android/px/model/InstructionAction.java
- px-services/src/main/java/com/mercadopago/android/px/model/Interaction.java
Se agrega la posibilidad de que la Congrat tenga instrucciones que soportan acciones, ya sea abrir una url en navegador o copiar el contenido de la instruction
Necesitamos agregarle utilidad a las instrucciones de la congrat screen
Se agregaron "Interactions", un nuevo nodo en las Instructions. Dando la posibilidad de mostrar informacion y darle una accion a cada instruccion por separado.
Se agregaron los Components y Renderers pertinentes.
Iniciar una instancia de checkout con un usuario y Payment Methods que soporten instrucciones y desde backend (api de instrucciones) agregar el nodo interactions a la respuesta.
- Feature que no rompe firma
> [Feature] Review confirm interactions

- px-checkout/src/main/res/values-pt/strings.xml
Se modifico el wording del boton continuar para idioma portugués
Requerimiento de UX
> [Fix] Changing continue button's wording in poruguese

- CHANGELOG.md
- gradle.properties
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultErrorActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultSuccessActivity.java
Resuelve el crash que se genera al enviar un map inmutable en el tracking de la pantalla de congrats de asociación de tarjeta
Se cambio de inmutable a mutable
> [FIX] Card association crash on congrats

- .travis.yml
- build.gradle
- gradle.properties
- gradle/deploy_base.gradle
- px-checkout/src/androidTest/java/com/mercadopago/android/px/model/CardTokenTest.java
- scripts/cd_script.sh
Empieza a funcionar el comando "[ci deploy]" (como en plugin de meli) dentro del commit. Si tiene ese mensaje dentro del commit message va a generar un build y deploy en producción, previo taggeo.
A partir de ahora todos los PRs generan versiones experimentales. Para buscar el número ir al log de travis.
Por último, no es más necesario ponerle publish en bintray para terminar de publicar.
- Updated jacoco version
- Updated jfrog bintray gradle plugin
- added script for .travis
> [enhancement] better deploy scripts

- px-checkout/src/main/java/com/mercadopago/android/px/internal/util/textformatter/CFTFormatter.java
El CFT Formatter no contempla el caso en que el CFT sea null (por ejemplo en One tap MLB).
- Ahora si el porcentaje CFT es null o vacío no se muestra dicha descripción.
Iniciar el checkout con las [credenciales correspondientes de MLB sección Config](https://docs.google.com/spreadsheets/d/1EI5HdqQ_Oi8gG_YHFU9rXebdMujclcoP10QqfjhE3HU/edit#gid=1230229952).
> [Fix] One Tap MLB - "CFT: null"

- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/AmountDescriptorView.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/SummaryDetailDescriptorFactory.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/SoldOutDiscountDetailColor.java
- px-checkout/src/main/res/values/colors.xml
Se modifico la lógica de aplicación del color en la row de sold out discount de Summary View. 
En MP tiene que tener el mismo color que la row del descuento, mientras que en Meli tiene que tener el mismo color que el texto que dice "Tu compra".
> [enhancement] Sold out discount color

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmPresenter.java
En descuentos por medio de pago, al elegir en en la pantalla de grupos el medio de pago que tiene descuentos y luego en la pantalla de revisa y confirma se elige cambiar el medio de pago, figura en la pantalla de grupos el descuento a nivel general mostrandolo en el footer de amount.
- Se hace un reset de UserSelectionRepository al momento de elegir cambiar el medio de pago.
- Con un collector que tenga descuentos en un medio de pago determinado, elegir dicho medio de pago
- En la pantalla de revisa y confirma, elegir cambiar medio de pago.
> [fix] clear user selection on change payment method

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultErrorActivity.java
Este cambio resuelve el crash producido al ir por el flujo de error de almacenamiento de tarjeta y reintentar.
se implementa la nueva firma para la creacion del flujo de tarjeta 
en la pantalla de error al asociar la tarjeta se presiona en reintentar
> [hotfix] Retry card storage

- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodComponent.java
En la pantalla de congrats se está mostrando el transactionAmount que es el mismo en todos los payment data, hay que usar rawAmount.
- Cambio transactionAmount por rawAmount en el armado de la pantalla de congrats
- Generar un pago exitoso con split payment
> [fix] split payment congrats amount

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
Al hacer back en la pantalla de payment vault, luego de haber elegido cambiar medio de pago en la pantalla de recuperos y rechazos, el botón de pagar en one tap queda en progreso indefinidamente y no deja al usuario hacer más nada.
- Se quita el uso de FragmentUtil el cual válida que sea visible y al momento de cancelar el loading nos interesa si ya terminó y no si es visible.
- Generar un pago con Payment.StatusCodes.STATUS_REJECTED y Payment.StatusDetail.STATUS_DETAIL_CC_REJECTED_HIGH_RISK o cualquier combinación que te permita cambiar el medio de pago en recuperos y rechazos.
- Al ingresar a payment vault para seleccionar el medio de pago, hacer back.
> [fix] on payment vault back after reject & recover payment change, keeps one tap button in progress

- px-checkout/src/main/java/com/mercadopago/android/px/internal/util/CircleTransform.java
- px-checkout/src/test/java/com/mercadopago/android/px/paymentvault/PaymentVaultPresenterTest.java
Crasheaba el Summary de One Tap cuando la imagen del collector es un GIF.
> Avoid crashing on Circle Transform without source config

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/CheckoutPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/navigation/OnChangePaymentMethodDriver.java
Cuando caemos en un resultado de error pagando en un flujo de one tap, al intentar cambiar el método de pago nos lleva a la selección por grupo. Queremos que si es one tap no nos saque de ese flujo.
> Added change payment method driver to keep one tap flow after payment rejection

- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardPaymentPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/IssuersSolver.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/SummaryAmountListener.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/installments/PayerCostSolver.java
- px-checkout/src/test/java/com/mercadopago/android/px/guessing/GuessingCardPaymentPresenterTest.java
- px-checkout/src/test/java/com/mercadopago/android/px/internal/features/guessing_card/IssuersSolverTest.java
- px-checkout/src/test/java/com/mercadopago/android/px/internal/features/installments/PayerCostSolverTest.java
Con una preferencia de pago con default installments veíamos una pantalla en blanco en el flujo de pago, cuando chequeaba si tenía que mostrar la selección de cuotas o seguir adelante.
Hicimos un prefetch de installments y un select del el default installment en el repositorio local para evitar ese chequeo innecesario.
> Fetch and select default installment one step before to avoid InstallmentsActivity blank screen

- px-checkout/src/main/java/com/mercadopago/android/px/core/internal/MercadoPagoCardStorage.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/MPTracker.java
- px-services/src/main/java/com/mercadopago/android/px/internal/core/ApplicationModule.java
- px-services/src/main/java/com/mercadopago/android/px/internal/core/SessionIdProvider.java
Se generaban múltiples session_id en el interceptor de los request.
> [hotfix] Fixed tracking of session_id

- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ResultViewTrackModel.java
La estructura del track que se enviaba en PaymentResult no era la correcta.
Se están generando tracks inválidos.
- Se sacaron los atributos payment_method_id y payment_method_type de available methods y se los colocó en el mismo nivel que el resto de los atributos. 
- El atributo available_methods no se envía más en los tracks de PaymentResult.
- El atributo extra_info no se envía en los tracks de PaymentResult. Antes se estaba enviando en null. Es un campo no requerido en Melidata. 
Crear un PXTrackingListener, setearlo en MPTracker y loguear los tracks.
> [hotfix] Fixed payment result tracking

- px-checkout/src/main/java/com/mercadopago/android/px/internal/util/ViewUtils.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodBodyComponent.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodComponent.java
El layout de cada método de pago en la Congrats tenía ciertos problemas, mostraba una view fantasma que a veces no iba y no centraba correctamente si había espacio.
> Fix payment result methods layout

- px-testlib/src/main/java/com/mercadopago/android/px/testcheckout/assertions/ProcessorValidator.java
- testlib/src/main/java/com/mercadopago/android/testlib/idlingresource/ActivityIdlingResource.java
Se agrega ProcessorValidator a px-testlib para poder incluir validaciones de la procesadora de pago en los test de regresión.
Se fixea lógica en ActivityIdlingResource donde se podía producir una excepción si el iterador está vacío
> [enhancement] add validator for payment processors

- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CardAssociationService.java
- px-services/src/main/java/com/mercadopago/android/px/internal/services/CardService.java
Se elimina la variable de path del endpoint de card_issuers usado en alta de tarjeta exclusivamente, debido a que este endpoint no es nuestro y no tenemos un beta para probar, lo que ocasiona que falle la alta de tarjeta contra beta. Se fija el path directamente a v1.
> [fix] remove path variable from card issuers service

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
En one tap, el botón de confirmar payment no se llega a actualizar al presionarlo y permite presionarlo varias veces.
* Se hace un setClickable(false) en el primer click
* El estado del botón se recupera en el update de ConfirmButtonAdapter
> [fix] double payment in one tap

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmActivity.java
Se modifica el flujo para mostrar la pantalla de security code para tarjetas guardadas desde one tap.
* Antes el flujo pasaba por CardVaultActivity
* Ahora va directo de ExpressPaymentFragment a SecurityCodeActivity
> [enhancement] killing card vault #1

- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/SelectMethodData.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/views/OneTapViewTest.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/views/SelectMethodViewTest.java
Se agrega el trackeo del atributo available_methods_quantity para trackear la cantidad de medios de pagos que se le ofrecieron al usuario en checkout Express. 
Facilitar las queries.
> [feature] Available methods quantity tracking

- gradle/deploy_base.gradle
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ConfirmEvent.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/ConfirmData.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/SelectMethodData.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/events/ConfirmEventTest.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/views/OneTapViewTest.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/views/SelectMethodViewTest.java
Se agrega el trackeo de la posición del medio de pago seleccionado en Express Payment.
Optimizar las queries en el análisis de la info obtenida en los tracks.
En el Confirm event se agregó el atributo paymentMethodSelectedIndex. 
Realizar un pago con Express Payment y observar en el log del track que el atributo es correcto.
> [feature] Added payment method index tracking

- px-services/src/main/java/com/mercadopago/android/px/preferences/CheckoutPreference.java
Se agrega el collector Id a la clase CheckoutPreference debido a que hay integradores que necesitan saber este dato al momento de realizar el pago.
El collectorId es un atributo que ya viene en la CheckoutPreference de meli.
> [enhancement] add collector id in CheckoutPreference

- px-checkout/src/main/java/com/mercadopago/android/px/internal/base/PXActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/ErrorActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/IssuersActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/PaymentTypesActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/SecurityCodeActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/TermsAndConditionsActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/bank_deal_detail/BankDealDetailActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/bank_deals/BankDealsActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/business_result/BusinessPaymentResultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/cardvault/CardVaultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/GuessingCardActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultErrorActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/guessing_card/card_association_result/CardAssociationResultSuccessActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/installments/InstallmentsActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payer_information/PayerInformationActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_methods/PaymentMethodsActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_vault/PaymentVaultActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/plugins/PaymentProcessorActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_and_confirm/ReviewAndConfirmActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/review_payment_methods/ReviewPaymentMethodsActivity.java
Este cambio resuelve dos problemas:
* Salir del checkout de una forma amigable cuando el estado de la sesión es inconsistente debido a que posiblemente haya muerto el Application
* Algunos memory leaks debido a que no todos los presenters se estaban desvinculando de la vista debidamente.
> [fix] check session state to exit gracefully

- px-checkout/src/main/res/layout/px_activity_payment_result.xml
Espacio en blanco cuando se scrollea para abajo en la congrats.
Se agrego el android:overScrollMode="never" para que no permita hacer el bounce al scrollear
Llegar hasta la congrats y scrollear para arriba y para abajo
> Fix Overscrolling header space

- px-checkout/src/main/res/layout/px_business_components.xml
Volvemos a los márgenes originales, cambiamos como se acomoda el componente de descuento a lo largo.
Debido al refactor del componente de descuento debemos volver a los márgenes originales y cambiar de wrap_content a match_parent.
> change width and margin of discount view

- example/src/main/java/com/mercadopago/android/px/utils/OneTapSamples.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/DefaultPaymentProcessor.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/SplitPaymentHeaderAdapter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ViewAdapter.java
- Se saca el true de que soportamos split en la procesadora default.
- La view de split se mostraba cuando no debía en algunos casos después de la animación del alta nuevo.
- También le puse descuento always on al merchant que lo tenía antes, y lo dejé para el ejemplo uno de one tap.
> Fixed card form split animation

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java
Bug que hacía romper el nuevo alta de tarjeta.
Al tener destroy-activities el método showOneTap se llamaba siempre, haciendo que el fragment de OneTap se agregue nuevamente al stack. Entonces sí CardForm estaba en el tope de la pila, este pasaba en segundo lugar al agregar nuevamente OneTap.
Link Bugsnag: https://app.bugsnag.com/mercadolibre/mercado-pago-android/errors?filters[event.since][0][type]=eq&filters[event.since][0][value]=all&filters[app.release_stage][0][type]=eq&filters[app.release_stage][0][value]=production&filters[event.severity][0][type]=eq&filters[event.severity][0][value]=error&filters[search][0][type]=eq&filters[search][0][value]=cardform&filters[search][1][type]=eq&filters[search][1][value]=NullPointerException&filters[error.status][0][type]=eq&filters[error.status][0][ …
> [FIX] fixed nullpointer in cardform

- example/src/main/java/com/mercadopago/SamplePaymentProcessor.java
- example/src/main/java/com/mercadopago/SamplePaymentProcessorNoView.java
- example/src/main/java/com/mercadopago/android/px/utils/OneTapSamples.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/mappers/PaymentResultRemediesModelMapper.kt
- px-checkout/src/main/java/com/mercadopago/android/px/internal/util/TokenCreationWrapper.kt
- Decía "Tarjeta terminada en NULL" después de un recupero de los nuevos de CVV.
- La procesadora del example soporta una lista de pagos.
> [Fix] Last four digits null after cvv remedy

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPayment.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentFragment.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/ExpressPaymentPresenter.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/TargetBehaviourEvent.kt
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/TargetBehaviourTrackData.kt
- px-services/src/main/java/com/mercadopago/android/px/model/one_tap/CheckoutBehaviour.kt
In addition to modals handled in checkout behaviour, now the behaviour could be a simple target (a deepLink) to be opened
> [feature] target behaviour

- px-addons/src/main/java/com/mercadopago/android/px/addons/model/internal/SecurityType.kt
- px-checkout/src/main/java/com/mercadopago/android/px/core/PaymentProcessor.java
- px-checkout/src/main/java/com/mercadopago/android/px/core/SplitPaymentProcessor.java
- px-checkout/src/main/java/com/mercadopago/android/px/core/internal/CheckoutDataMapper.java
- px-checkout/src/main/java/com/mercadopago/android/px/core/internal/PaymentProcessorMapper.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentService.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentSettingService.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/plugins/PaymentProcessorActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PaymentSettingRepository.java
Se nos requirió a PX enviar un flag al momento de pagar como indicativo de si se le pidió o no al usuario validación durante el pago. Agregamos en la firma de la procesadora un atributo nuevo con este flag (securityType), para que los integradores lo propaguen a sus backends y posteriormente a payments. El dato se debe enviar a payments de la siguiente manera:
header {X-Tracking-Id=[platform:v1-whitelabel,operatingSystem:ALL,type:N/A,**securty:2fa**]}
Es decir, lo que se agrega a la llamada es "**security:2fa**" en ese header. En el caso que el flag indique que no hubo seguridad debería viajar como "security:none".
> [feature] add security type to signature of SplitPaymentProcessor

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/view/RetryPaymentFragment.kt
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodDescriptorView.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentMethodHeaderView.java
Vistas duplicadas, crash en remedy de silver bullet.
Se duplican las vistas de los experimentos cuando vuelvo de remedies, se soluciona crash con silver bullet.
1er bug: Aparece un remedy, botón seleccionar otro medio de pago, retorno a onetap.
2do bug: Con remedy Silverbullet
> [Fix] Duplicate view and crash in silver bullet fixed

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodFragment.java
Crash en remedies cuando esta habilitado talkback.
El error ocurre cuando estamos tratando de castear el parent de la vista a un DynamicHeightViewPager. Este parent no coincide cuando estamos en remedies.
> [Fix] Bug fixed

- example/src/main/java/com/mercadopago/SamplePaymentProcessor.kt
- px-checkout/src/main/java/com/mercadopago/android/px/core/internal/MercadoPagoCardStorage.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentSettingService.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PaymentSettingRepository.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/PXTracker.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/views/OneTapViewTest.java
- px-services/src/main/java/com/mercadopago/android/px/internal/di/ConfigurationModule.kt
- px-services/src/main/java/com/mercadopago/android/px/internal/tracking/FlowProvider.kt
- px-services/src/main/java/com/mercadopago/android/px/internal/tracking/LegacyFlowProvider.kt
- px-services/src/main/java/com/mercadopago/android/px/internal/tracking/TrackingRepository.kt
- px-services/src/main/java/com/mercadopago/android/px/internal/tracking/TrackingRepositoryHelper.kt
- px-services/src/main/java/com/mercadopago/android/px/internal/tracking/TrackingRepositoryImpl.kt
- Se saca el chequeo de si la sesión está inicializada, se chequea si es válida la procesadora de pagos.
- Se persiste el seteo legacy de tracking para que no se pierda al morir la aplicación.
> [Feature] Removed session initialized check, improved legacy tracking support

- px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentSettingService.java
- No se toma como válido un posible PaymentConfiguration null.
> [Fix] Payment configuration is not valid if null

- px-services/src/main/java/com/mercadopago/android/px/preferences/PostPaymentUrls.kt
- Se hace serializable la clase PostPaymentUrls
> [Fix] Make PostPaymentUrls serializable

- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.kt
Se agrega validación para no enviar remedies cuando la congrats viene por el flujo de PaymentCongratsModel
> Remedies fix for PCM flow

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModel.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/model/PaymentCongratsModelMapper.java
- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/views/ResultViewTrack.kt
Se arregla que si viene por una standaloneCongrats se trackee por /payment_congrats y si no se trackea por /px_checkout
> [Fix] PaymentCongratstrack fix

- px-services/src/main/java/com/mercadopago/android/px/internal/util/JsonUtil.kt
- JsonSyntaxException is resolved when we save complex keys in map
> [Fix] JsonSyntaxException is resolved when we save complex keys in map

- px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/model/AvailableMethod.java
- px-checkout/src/test/java/com/mercadopago/android/px/tracking/internal/events/ConfirmEventTest.java
el nombre original era la mejor opcion pero lamentablemente internamente melidata usa esos nombres y nos pisan el nodo con otra información, por lo que nos vimos obligados a agregarle algo mas al nombre.
> [fix] change applications field name to methods_applications

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/Checkout.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
This fixes the crash showing one tap after on restore when there was an error.
> [Fix] Saves checkout presenter screen state

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/validation_program/ValidationProgramUseCase.kt
- px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
Firma acordada con backend:
`"status": {
"enabled": "false",
"reason": ""
}`
Debemos aplicar el primer validation program que venga habilitado.
> [enhancement] Add status to validation programs

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodFragment.java
The  app crashes after the flow of displaying a dialog from a disabled card and when clicking again when enabled.
This fix prevents the application from crashing after clicking an enabled card after viewing the dialog box with a payment option disabled.
Added a if statement in the enable() method in the PaymentMethodFragment class to remove and clear the setOnClickListener if it didn't pass the if. Without this treatment, the reference of the listener in the disable() method causes the crash.
Mock for test: https://run.mocky.io/v3/fe1eb0a6-8f57-43c6-a124-82e7f36bf5eb
- Select a credit card and change to débit payment. 
- Click on the card to show dialog explain which is not possible occurs payment with this option. 
- Change to credit payment
- Click again in the card and the crash will …
> [PXN-2186] - Fix Resource Not Found Exception

- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/TermsAndConditionsActivity.java
Changes were made to the TermsAndConditionsActivity class to display the MLM TyCs without redirecting the Mercado Livre login page. These changes also work for the MLB TyC page, which also had issues displaying terms as well.
Show terms and conditions of use of the mercado crédito when selected on one tap. 
- In onetap, select "mercado crédito" option. 
- click in "términos y condiciones" option to show webview page. 
- select "carátula y domiciliación" or "terminos y condiciones"
**MLM - ERROR:**
https://ibb.co/4ZnG102
**MLM - FIX**
https://ibb.co/YbDTkZ6
> [PXN-2265] Fix - TyC de credits MLM

- CHANGELOG.md
- gradle.properties
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutActivity.java
* FIX - NullPointerException is fixed when the checkout is started by onNewIntent.
> [Release] 4.96.2

- CHANGELOG.md
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsDeepLinkActivity.kt
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.kt
The method that opens our congrats was duplicated in order to remove the line that cleans the session in order to keep it available for followings calls.
For semovi flow the integrator was opening our congrats twice, what implies a crash because the session was cleaned with the first attempt.
1- Remove the finish() invocation on PostpaymentSampleActivity::32
2- Launch a PostPaymentFlow already configured in the test app
3- Try to navigate til the congrats screen
4- Close and reopen the congrats 
The app shouldn't crash when we open the congrats more than one time
Error | Solution
-----|-----
> [Fix]: PXN-3379  New method is added to keep session.

- CHANGELOG.md
- px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
The exception was thrown because a swipe was performed in between the biometric validation.
To be able to make a payment with the payment method chosen at the time of pressing the 'PayButton' instead of the one that is selected after doing swipe.
https://app.bugsnag.com/mercadolibre/mercado-pago-android/errors/620abf99279f330007614d87
Instead of using the index of the current element we use the ID of the 'PaymentConfiguration'.
The 'payerCost' of AM is null, and for credit cards can't be.
When using 'getCurrentOneTapItem()' the ID was a credit card one, so the exception happened because PaymentTypes expected a credit card with installments and found a null.
To reproduce the behavior, you must display the AM payment method, press the pay button and do a quick swipe before the biometric …
> [Fix] getInstallments()- NullPointerException
